INSERT INTO countries (id,name) VALUES (1,'Австралия');
INSERT INTO countries (id,name) VALUES (2,'Австрия');
INSERT INTO countries (id,name) VALUES (3,'Азербайджан');
INSERT INTO countries (id,name) VALUES (4,'Акротири');
INSERT INTO countries (id,name) VALUES (5,'Албания');
INSERT INTO countries (id,name) VALUES (6,'Алжир');
INSERT INTO countries (id,name) VALUES (7,'Американское Самоа');
INSERT INTO countries (id,name) VALUES (8,'Ангилья');
INSERT INTO countries (id,name) VALUES (9,'Ангола');
INSERT INTO countries (id,name) VALUES (10,'Андорра');
INSERT INTO countries (id,name) VALUES (11,'Антигуа и Барбуда');
INSERT INTO countries (id,name) VALUES (12,'Аргентина');
INSERT INTO countries (id,name) VALUES (13,'Армения');
INSERT INTO countries (id,name) VALUES (14,'Аруба');
INSERT INTO countries (id,name) VALUES (15,'Афганистан');
INSERT INTO countries (id,name) VALUES (16,'Багамские Острова');
INSERT INTO countries (id,name) VALUES (17,'Бангладеш');
INSERT INTO countries (id,name) VALUES (18,'Барбадос');
INSERT INTO countries (id,name) VALUES (19,'Бахрейн');
INSERT INTO countries (id,name) VALUES (20,'Белиз');
INSERT INTO countries (id,name) VALUES (21,'Белоруссия');
INSERT INTO countries (id,name) VALUES (22,'Бельгия');
INSERT INTO countries (id,name) VALUES (23,'Бенин');
INSERT INTO countries (id,name) VALUES (24,'Бермудские Острова');
INSERT INTO countries (id,name) VALUES (25,'Болгария');
INSERT INTO countries (id,name) VALUES (26,'Боливия');
INSERT INTO countries (id,name) VALUES (27,'Босния и Герцеговина');
INSERT INTO countries (id,name) VALUES (28,'Ботсвана');
INSERT INTO countries (id,name) VALUES (29,'Бразилия');
INSERT INTO countries (id,name) VALUES (30,'Британская территория в Индийском океане');
INSERT INTO countries (id,name) VALUES (31,'Британские Виргинские острова');
INSERT INTO countries (id,name) VALUES (32,'Бруней');
INSERT INTO countries (id,name) VALUES (33,'Буркина-Фасо');
INSERT INTO countries (id,name) VALUES (34,'Бурунди');
INSERT INTO countries (id,name) VALUES (35,'Бутан');
INSERT INTO countries (id,name) VALUES (36,'Вануату');
INSERT INTO countries (id,name) VALUES (37,'Ватикан');
INSERT INTO countries (id,name) VALUES (38,'Великобритания');
INSERT INTO countries (id,name) VALUES (39,'Венгрия');
INSERT INTO countries (id,name) VALUES (40,'Венесуэла');
INSERT INTO countries (id,name) VALUES (41,'Виргинские Острова');
INSERT INTO countries (id,name) VALUES (42,'Восточный Тимор');
INSERT INTO countries (id,name) VALUES (43,'Вьетнам');
INSERT INTO countries (id,name) VALUES (44,'Габон');
INSERT INTO countries (id,name) VALUES (45,'Гаити');
INSERT INTO countries (id,name) VALUES (46,'Гайана');
INSERT INTO countries (id,name) VALUES (47,'Гамбия');
INSERT INTO countries (id,name) VALUES (48,'Гана');
INSERT INTO countries (id,name) VALUES (49,'Гваделупа');
INSERT INTO countries (id,name) VALUES (50,'Гватемала');
INSERT INTO countries (id,name) VALUES (51,'Гвинея');
INSERT INTO countries (id,name) VALUES (52,'Гвинея-Бисау');
INSERT INTO countries (id,name) VALUES (53,'Германия');
INSERT INTO countries (id,name) VALUES (54,'Гернси');
INSERT INTO countries (id,name) VALUES (55,'Гибралтар');
INSERT INTO countries (id,name) VALUES (56,'Гондурас');
INSERT INTO countries (id,name) VALUES (57,'Гонконг');
INSERT INTO countries (id,name) VALUES (58,'Гренада');
INSERT INTO countries (id,name) VALUES (59,'Гренландия');
INSERT INTO countries (id,name) VALUES (60,'Греция');
INSERT INTO countries (id,name) VALUES (61,'Грузия');
INSERT INTO countries (id,name) VALUES (62,'Гуам');
INSERT INTO countries (id,name) VALUES (63,'Дания');
INSERT INTO countries (id,name) VALUES (64,'Декелия');
INSERT INTO countries (id,name) VALUES (65,'Демократическая Республика Конго');
INSERT INTO countries (id,name) VALUES (66,'Джерси');
INSERT INTO countries (id,name) VALUES (67,'Джибути');
INSERT INTO countries (id,name) VALUES (68,'Доминика');
INSERT INTO countries (id,name) VALUES (69,'Доминиканская Республика');
INSERT INTO countries (id,name) VALUES (70,'Египет');
INSERT INTO countries (id,name) VALUES (71,'Замбия');
INSERT INTO countries (id,name) VALUES (72,'Западная Сахара');
INSERT INTO countries (id,name) VALUES (73,'Зимбабве');
INSERT INTO countries (id,name) VALUES (74,'Израиль');
INSERT INTO countries (id,name) VALUES (75,'Индия');
INSERT INTO countries (id,name) VALUES (76,'Индонезия');
INSERT INTO countries (id,name) VALUES (77,'Иордания');
INSERT INTO countries (id,name) VALUES (78,'Ирак');
INSERT INTO countries (id,name) VALUES (79,'Иран');
INSERT INTO countries (id,name) VALUES (80,'Ирландия');
INSERT INTO countries (id,name) VALUES (81,'Исландия');
INSERT INTO countries (id,name) VALUES (82,'Испания');
INSERT INTO countries (id,name) VALUES (83,'Италия');
INSERT INTO countries (id,name) VALUES (84,'Йемен');
INSERT INTO countries (id,name) VALUES (85,'Кабо-Верде');
INSERT INTO countries (id,name) VALUES (86,'Казахстан');
INSERT INTO countries (id,name) VALUES (87,'Каймановы острова');
INSERT INTO countries (id,name) VALUES (88,'Камбоджа');
INSERT INTO countries (id,name) VALUES (89,'Камерун');
INSERT INTO countries (id,name) VALUES (90,'Канада');
INSERT INTO countries (id,name) VALUES (91,'Катар');
INSERT INTO countries (id,name) VALUES (92,'Кения');
INSERT INTO countries (id,name) VALUES (93,'Кипр');
INSERT INTO countries (id,name) VALUES (94,'Киргизия');
INSERT INTO countries (id,name) VALUES (95,'Кирибати');
INSERT INTO countries (id,name) VALUES (96,'Китай');
INSERT INTO countries (id,name) VALUES (97,'Кокосовые острова');
INSERT INTO countries (id,name) VALUES (98,'Колумбия');
INSERT INTO countries (id,name) VALUES (99,'Коморы');
INSERT INTO countries (id,name) VALUES (100,'Косово');
INSERT INTO countries (id,name) VALUES (101,'Коста-Рика');
INSERT INTO countries (id,name) VALUES (102,'Кот-д''Ивуар');
INSERT INTO countries (id,name) VALUES (103,'Куба');
INSERT INTO countries (id,name) VALUES (104,'Кувейт');
INSERT INTO countries (id,name) VALUES (105,'Кюрасао');
INSERT INTO countries (id,name) VALUES (106,'Лаос');
INSERT INTO countries (id,name) VALUES (107,'Латвия');
INSERT INTO countries (id,name) VALUES (108,'Лесото');
INSERT INTO countries (id,name) VALUES (109,'Либерия');
INSERT INTO countries (id,name) VALUES (110,'Ливан');
INSERT INTO countries (id,name) VALUES (111,'Ливия');
INSERT INTO countries (id,name) VALUES (112,'Литва');
INSERT INTO countries (id,name) VALUES (113,'Лихтенштейн');
INSERT INTO countries (id,name) VALUES (114,'Люксембург');
INSERT INTO countries (id,name) VALUES (115,'Маврикий');
INSERT INTO countries (id,name) VALUES (116,'Мавритания');
INSERT INTO countries (id,name) VALUES (117,'Мадагаскар');
INSERT INTO countries (id,name) VALUES (118,'Майотта');
INSERT INTO countries (id,name) VALUES (119,'Макао');
INSERT INTO countries (id,name) VALUES (120,'Македония');
INSERT INTO countries (id,name) VALUES (121,'Малави');
INSERT INTO countries (id,name) VALUES (122,'Малайзия');
INSERT INTO countries (id,name) VALUES (123,'Мали');
INSERT INTO countries (id,name) VALUES (124,'Мальдивы');
INSERT INTO countries (id,name) VALUES (125,'Мальта');
INSERT INTO countries (id,name) VALUES (126,'Марокко');
INSERT INTO countries (id,name) VALUES (127,'Мартиника');
INSERT INTO countries (id,name) VALUES (128,'Маршалловы Острова');
INSERT INTO countries (id,name) VALUES (129,'Мексика');
INSERT INTO countries (id,name) VALUES (130,'Микронезия');
INSERT INTO countries (id,name) VALUES (131,'Мозамбик');
INSERT INTO countries (id,name) VALUES (132,'Молдова');
INSERT INTO countries (id,name) VALUES (133,'Монако');
INSERT INTO countries (id,name) VALUES (134,'Монголия');
INSERT INTO countries (id,name) VALUES (135,'Монтсератт');
INSERT INTO countries (id,name) VALUES (136,'Мьянма');
INSERT INTO countries (id,name) VALUES (137,'Намибия');
INSERT INTO countries (id,name) VALUES (138,'Науру');
INSERT INTO countries (id,name) VALUES (139,'Непал');
INSERT INTO countries (id,name) VALUES (140,'Нигер');
INSERT INTO countries (id,name) VALUES (141,'Нигерия');
INSERT INTO countries (id,name) VALUES (142,'Нидерландские Антильские острова');
INSERT INTO countries (id,name) VALUES (143,'Нидерланды');
INSERT INTO countries (id,name) VALUES (144,'Никарагуа');
INSERT INTO countries (id,name) VALUES (145,'Ниуэ');
INSERT INTO countries (id,name) VALUES (146,'Новая Зеландия');
INSERT INTO countries (id,name) VALUES (147,'Новая Каледония');
INSERT INTO countries (id,name) VALUES (148,'Норвегия');
INSERT INTO countries (id,name) VALUES (149,'Объединенные Арабские Эмираты');
INSERT INTO countries (id,name) VALUES (150,'Оман');
INSERT INTO countries (id,name) VALUES (151,'Остров Буве');
INSERT INTO countries (id,name) VALUES (152,'Остров Клиппертон');
INSERT INTO countries (id,name) VALUES (153,'Остров Мэн');
INSERT INTO countries (id,name) VALUES (154,'Остров Навасса');
INSERT INTO countries (id,name) VALUES (155,'Остров Рождества');
INSERT INTO countries (id,name) VALUES (156,'Остров Святой Елены, Остров Вознесения, и Тристан-да-Кунья');
INSERT INTO countries (id,name) VALUES (157,'Остров Уэйк');
INSERT INTO countries (id,name) VALUES (158,'Остров Херд и острова Макдональд');
INSERT INTO countries (id,name) VALUES (159,'Острова Ашмор и Картье');
INSERT INTO countries (id,name) VALUES (160,'Острова Кораллового моря');
INSERT INTO countries (id,name) VALUES (161,'Острова Кука');
INSERT INTO countries (id,name) VALUES (162,'Острова Питкэрн');
INSERT INTO countries (id,name) VALUES (163,'Пакистан');
INSERT INTO countries (id,name) VALUES (164,'Палау');
INSERT INTO countries (id,name) VALUES (165,'Панама');
INSERT INTO countries (id,name) VALUES (166,'Папуа - Новая Гвинея');
INSERT INTO countries (id,name) VALUES (167,'Парагвай');
INSERT INTO countries (id,name) VALUES (168,'Перу');
INSERT INTO countries (id,name) VALUES (169,'Польша');
INSERT INTO countries (id,name) VALUES (170,'Португалия');
INSERT INTO countries (id,name) VALUES (171,'Пуэрто-Рико');
INSERT INTO countries (id,name) VALUES (172,'Республика Конго');
INSERT INTO countries (id,name) VALUES (173,'Реюньон');
INSERT INTO countries (id,name) VALUES (174,'Россия');
INSERT INTO countries (id,name) VALUES (175,'Руанда');
INSERT INTO countries (id,name) VALUES (176,'Румыния');
INSERT INTO countries (id,name) VALUES (177,'Самоа');
INSERT INTO countries (id,name) VALUES (178,'Сан-Марино');
INSERT INTO countries (id,name) VALUES (179,'Сан-Томе и Принсипи');
INSERT INTO countries (id,name) VALUES (180,'Саудовская Аравия');
INSERT INTO countries (id,name) VALUES (181,'Свазиленд');
INSERT INTO countries (id,name) VALUES (182,'Северная Корея');
INSERT INTO countries (id,name) VALUES (183,'Северные Марианские острова');
INSERT INTO countries (id,name) VALUES (184,'Сейшельские Острова');
INSERT INTO countries (id,name) VALUES (185,'Сен-Бартелеми');
INSERT INTO countries (id,name) VALUES (186,'Сен-Мартен');
INSERT INTO countries (id,name) VALUES (187,'Сен-Пьер и Микелон');
INSERT INTO countries (id,name) VALUES (188,'Сенегал');
INSERT INTO countries (id,name) VALUES (189,'Сент-Винсент и Гренадины');
INSERT INTO countries (id,name) VALUES (190,'Сент-Китс и Невис');
INSERT INTO countries (id,name) VALUES (191,'Сент-Люсия');
INSERT INTO countries (id,name) VALUES (192,'Сербия');
INSERT INTO countries (id,name) VALUES (193,'Сингапур');
INSERT INTO countries (id,name) VALUES (194,'Синт-Мартен');
INSERT INTO countries (id,name) VALUES (195,'Сирия');
INSERT INTO countries (id,name) VALUES (196,'Словакия');
INSERT INTO countries (id,name) VALUES (197,'Словения');
INSERT INTO countries (id,name) VALUES (198,'Соединенные Штаты Америки');
INSERT INTO countries (id,name) VALUES (199,'Соломоновы Острова');
INSERT INTO countries (id,name) VALUES (200,'Сомали');
INSERT INTO countries (id,name) VALUES (201,'Судан');
INSERT INTO countries (id,name) VALUES (202,'Суринам');
INSERT INTO countries (id,name) VALUES (203,'Сьерра-Леоне');
INSERT INTO countries (id,name) VALUES (204,'Таджикистан');
INSERT INTO countries (id,name) VALUES (205,'Таиланд');
INSERT INTO countries (id,name) VALUES (206,'Тайвань');
INSERT INTO countries (id,name) VALUES (207,'Танзания');
INSERT INTO countries (id,name) VALUES (208,'Теркс и Кайкос');
INSERT INTO countries (id,name) VALUES (209,'Того');
INSERT INTO countries (id,name) VALUES (210,'Токелау');
INSERT INTO countries (id,name) VALUES (211,'Тонга');
INSERT INTO countries (id,name) VALUES (212,'Тринидад и Тобаго');
INSERT INTO countries (id,name) VALUES (213,'Тувалу');
INSERT INTO countries (id,name) VALUES (214,'Тунис');
INSERT INTO countries (id,name) VALUES (215,'Туркменистан');
INSERT INTO countries (id,name) VALUES (216,'Турция');
INSERT INTO countries (id,name) VALUES (217,'Уганда');
INSERT INTO countries (id,name) VALUES (218,'Узбекистан');
INSERT INTO countries (id,name) VALUES (219,'Украина');
INSERT INTO countries (id,name) VALUES (220,'Уоллис и Футуна');
INSERT INTO countries (id,name) VALUES (221,'Уругвай');
INSERT INTO countries (id,name) VALUES (222,'Фарерские острова');
INSERT INTO countries (id,name) VALUES (223,'Фиджи');
INSERT INTO countries (id,name) VALUES (224,'Филиппины');
INSERT INTO countries (id,name) VALUES (225,'Финляндия');
INSERT INTO countries (id,name) VALUES (226,'Фолклендские острова');
INSERT INTO countries (id,name) VALUES (227,'Франция');
INSERT INTO countries (id,name) VALUES (228,'Французская Гвиана');
INSERT INTO countries (id,name) VALUES (229,'Французская Полинезия');
INSERT INTO countries (id,name) VALUES (230,'Французские Южные и Антарктические территории');
INSERT INTO countries (id,name) VALUES (231,'Хорватия');
INSERT INTO countries (id,name) VALUES (232,'Центральноафриканская Республика');
INSERT INTO countries (id,name) VALUES (233,'Чад');
INSERT INTO countries (id,name) VALUES (234,'Черногория');
INSERT INTO countries (id,name) VALUES (235,'Чехия');
INSERT INTO countries (id,name) VALUES (236,'Чили');
INSERT INTO countries (id,name) VALUES (237,'Швейцария');
INSERT INTO countries (id,name) VALUES (238,'Швеция');
INSERT INTO countries (id,name) VALUES (239,'Шпицберген');
INSERT INTO countries (id,name) VALUES (240,'Шри-Ланка');
INSERT INTO countries (id,name) VALUES (241,'Эквадор');
INSERT INTO countries (id,name) VALUES (242,'Экваториальная Гвинея');
INSERT INTO countries (id,name) VALUES (243,'Эль-Сальвадор');
INSERT INTO countries (id,name) VALUES (244,'Эритрея');
INSERT INTO countries (id,name) VALUES (245,'Эстония');
INSERT INTO countries (id,name) VALUES (246,'Эфиопия');
INSERT INTO countries (id,name) VALUES (247,'Южная Африка');
INSERT INTO countries (id,name) VALUES (248,'Южная Георгия и Южные Сандвичевы острова');
INSERT INTO countries (id,name) VALUES (249,'Южная Корея');
INSERT INTO countries (id,name) VALUES (250,'Южный Судан');
INSERT INTO countries (id,name) VALUES (251,'Ямайка');
INSERT INTO countries (id,name) VALUES (252,'Ян-Майен');
INSERT INTO countries (id,name) VALUES (253,'Япония');