INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (1,'Казахский национальный медицинский университет  им. С. Асфендиярова',3, 49);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (2,'Назарбаев университет',3, 50);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (3,'Восточно-Казахстанский  государственный университет им. С. Аманжолова',3, 51);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (4,'Казахский гуманитарно-юридический инновационный университет',3, 52);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (5,'Казахстанская инженерная, финансово-экономическая академия',3, 53);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (6,'Казахстанско-Немецкий университет',3, 54);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (7,'Жезказганский университет им. О.А.Байконурова',3, 55);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (8,'Медицинский университет Астана',3, 57);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (9,'Казахский экономический университет им. Т. Рыскулова',3, 58);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (10,'Карагандинский государственный медицинский университет',3, 59);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (11,'Кокшетауский государственный  университет им. Ш. Уалиханова',3, 60);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (12,'Костанайский государственный университет им. А. Байтурсынова',3, 61);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (13,'Академия экономики и права',3, 61);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (14,'Атырауский инженерно-гуманитарный институт',3, 62);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (15,'Гуманитарно-техническая академия',3, 63);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (16,'Алматинская академия МВД РК',3, 64);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (17,'Военный институт Внутренних войск МВД РК',3, 65);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (18,'Северо-Казахстанский государственный университет им. М. Козыбаева',3, 66);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (19,'Южно-Казахстанский государственный педагогический институт',3, 67);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (20,'Казахский национальный педагогический  университет им. Абая',3, 68);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (21,'Жамбылский гуманитарно-технический университет',3, 69);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (22,'Каспийский общественный университет',3, 70);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (23,'Таразский инновационно-гуманитарный университет',3, 71);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (24,'Университет «Мирас»',3, 72);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (25,'Университет международного бизнеса',3, 73);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (26,'Южно-Казахстанский гуманитарный институт им. М. Сапарбаева',3, 74);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (27,'Карагандинская академия МВД РК имени Б.Бейсенова',3, 75);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (28,'Военно-инженерный институт радиоэлектроники и связи МО РК',3, 76);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (29,'Актюбинский юридический институт МВД РК',3, 77);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (30,'Академия экономики и права им. О. Джолдасбекова',3, 78);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (31,'Университет Алматы',3, 79);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (32,'Гуманитарно-технический институт «Акмешит»',3, 80);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (33,'Актюбинский государственный региональный  университет им. К. Жубанова',3, 81);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (34,'Восточно-Казахстанский государственный технический университет им. Д.Серикбаева',3, 82);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (35,'Западно-Казахстанский инженерно-гуманитарный университет',3, 83);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (36,'Казахский университет экономики, финансов и международной торговли',3, 84);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (37,'Академия гражданской авиации',3, 85);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (38,'Казахский агротехнический университет им. С. Сейфуллина',3, 86);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (39,'Государственный медицинский университет города Семей',3, 87);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (40,'Национальный университет обороны',3, 88);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (41,'Карагандинский государственный индустриальный университет',3, 89);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (42,'Костанайский государственный педагогический институт',3, 90);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (43,'Казахстанский университет технологии и бизнеса',3, 91);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (44,'Казахстанско-Российский медицинский университет',3, 92);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (45,'Кызылординский государственный университет им. Коркыт Ата',3, 93);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (46,'Казахская национальная консерватория им. Курмангазы',3, 94);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (47,'Кокшетауский университет им. Абая Мырзахметова',3, 95);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (48,'Таразский технический институт',3, 96);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (49,'Университет «Сырдария»',3, 97);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (50,'Университет «Туран-Астана»',3, 98);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (51,'Центрально-Азиатский университет',3, 99);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (52,'Военный институт сил воздушной обороны имени дважды героя Советского Союза Т.Я.Бигельдинова МО РК',3, 100);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (53,'Казахская академия транспорта и коммуникаций им. М. Тынышпаева',3, 101);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (54,'Финансовая академия',3, 102);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (55,'Актюбинский университет им. С. Баишева',3, 103);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (56,'Евразийский гуманитарный институт',3, 104);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (57,'Аркалыкский государственный педагогический институт им. И.Алтынсарина',3, 105);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (58,'Жетысуский государственный университет им. И. Жансугурова',3, 106);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (59,'Государственный университет им. Шакарима г.Семей',3, 107);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (60,'Костанайская академия МВД РК',3, 108);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (61,'Евразийский  национальный университет им. Л.Н. Гумилева',3, 109);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (62,'Казахский национальный университет искусств',3, 110);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (63,'Алматинский университет энергетики и связи',3, 111);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (64,'Алматинский технологический университет',3, 112);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (65,'Западно-Казахстанский аграрно-технический университет им. Жангир хана',3, 113);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (66,'Карагандинский государственный технический университет',3, 114);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (67,'Павлодарский государственный педагогический институт',3, 115);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (68,'Академия пограничной службы КНБ РК',3, 116);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (69,'Инновационный Евразийский университет',3, 117);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (70,'Казахско-Китайская академия',3, 118);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (71,'Казахстанско-Американский свободный университет',3, 119);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (73,'Костанайский инженерно-педагогический университет им. Дулатова',3, 120);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (74,'Университет «Астана»',3, 121);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (75,'Университет «Туран»',3, 122);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (76,'Гуманитарный университет транспорта и права им. Д. Кунаева',3, 123);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (77,'Центрально-Казахстанская академия',3, 124);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (78,'Таразский государственный педагогический институт',3, 125);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (79,'Южно-Казахстанская государственная фармацевтическая академия',3, 126);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (81,'Египетский университет Исламской культуры «Нур-Мубарак»',3, 127);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (82,'Казахская академия труда и социальных отношений',3, 128);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (83,'Казахский инновационный университет',3, 129);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (84,'Международный университет информационных технологий',3, 130);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (85,'Алматинская академия экономики и статистики',3, 131);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (86,'Казахская  национальная академия искусств им. Т. Жургенова',3, 132);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (87,'Атырауский государственный университет им. Х. Досмухамедова',3, 133);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (88,'Кокшетауский технический институт МЧС РК',3, 134);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (89,'Международная образовательная корпорация',3, 135);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (90,'Западно-Казахстанский государственный университет им. М. Утемисова',3, 136);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (91,'Карагандинский государственный университет им. Е. Букетова',3, 137);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (92,'Университет КИМЭП',3, 138);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (93,'Казахский гуманитарно-юридический университет',3, 139);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (94,'Западно-Казахстанский государственный медицинский университет им. М. Оспанова',3, 140);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (95,'Павлодарский государственный университет им. С. Торайгырова',3, 141);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (96,'Казахский национальный университет им.аль-Фараби',3, 142);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (97,'Казахско-русский международный университет',3, 143);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (98,'Карагандинский университет «Болашак»',3, 144);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (99,'Костанайский социально-технический университет им. Зулхарнай Алдамжара',3, 145);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (100,'Международная академия бизнеса',3, 146);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (101,'Университет «Болашак»',3, 147);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (102,'Университет им. Сулеймана Демиреля',3, 148);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (103,'Региональный социально-инновационный университет',3, 149);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (104,'Военный институт Сухопутных войск МО РК',3, 150);
INSERT INTO educational_institutions (id,name,education_institution_type_id,street_id) VALUES (105,'Казахский университет международных отношений и мировых языков им. Абылай хана',3, 151);