INSERT INTO nationalities (id,name) VALUES (1,'абадзехи');
INSERT INTO nationalities (id,name) VALUES (2,'абаза');
INSERT INTO nationalities (id,name) VALUES (3,'абазины');
INSERT INTO nationalities (id,name) VALUES (4,'абжуйцы');
INSERT INTO nationalities (id,name) VALUES (5,'абхазы');
INSERT INTO nationalities (id,name) VALUES (6,'аварал');
INSERT INTO nationalities (id,name) VALUES (7,'аварцы');
INSERT INTO nationalities (id,name) VALUES (8,'австрийцы');
INSERT INTO nationalities (id,name) VALUES (9,'агинцы');
INSERT INTO nationalities (id,name) VALUES (10,'агул шуй');
INSERT INTO nationalities (id,name) VALUES (11,'агулар');
INSERT INTO nationalities (id,name) VALUES (12,'агульцы');
INSERT INTO nationalities (id,name) VALUES (13,'агулы');
INSERT INTO nationalities (id,name) VALUES (14,'адай');
INSERT INTO nationalities (id,name) VALUES (15,'аджарели');
INSERT INTO nationalities (id,name) VALUES (16,'аджарцы');
INSERT INTO nationalities (id,name) VALUES (17,'адыгейцы');
INSERT INTO nationalities (id,name) VALUES (18,'адыгэ (с родным языком адыгейским)');
INSERT INTO nationalities (id,name) VALUES (19,'адыгэ (с родным языком кабардинским)');
INSERT INTO nationalities (id,name) VALUES (20,'адыгэ (с родным языком черкесским)');
INSERT INTO nationalities (id,name) VALUES (21,'азербайджанлы');
INSERT INTO nationalities (id,name) VALUES (22,'азербайджанлылар');
INSERT INTO nationalities (id,name) VALUES (23,'азербайджанцы');
INSERT INTO nationalities (id,name) VALUES (24,'айсоры');
INSERT INTO nationalities (id,name) VALUES (25,'аккинцы');
INSERT INTO nationalities (id,name) VALUES (26,'алабугатские татары');
INSERT INTO nationalities (id,name) VALUES (27,'алаи');
INSERT INTO nationalities (id,name) VALUES (28,'албанцы');
INSERT INTO nationalities (id,name) VALUES (29,'алеуты');
INSERT INTO nationalities (id,name) VALUES (30,'алжирцы');
INSERT INTO nationalities (id,name) VALUES (31,'алтай-кижи');
INSERT INTO nationalities (id,name) VALUES (32,'алтайцы');
INSERT INTO nationalities (id,name) VALUES (33,'алтына куманды');
INSERT INTO nationalities (id,name) VALUES (34,'алутальу');
INSERT INTO nationalities (id,name) VALUES (35,'алюторцы');
INSERT INTO nationalities (id,name) VALUES (36,'амгун бэйенин');
INSERT INTO nationalities (id,name) VALUES (37,'американцы');
INSERT INTO nationalities (id,name) VALUES (38,'анатри');
INSERT INTO nationalities (id,name) VALUES (39,'ангагинас');
INSERT INTO nationalities (id,name) VALUES (40,'англичане');
INSERT INTO nationalities (id,name) VALUES (41,'андал');
INSERT INTO nationalities (id,name) VALUES (42,'андии');
INSERT INTO nationalities (id,name) VALUES (43,'андийцы');
INSERT INTO nationalities (id,name) VALUES (44,'анкалгакку');
INSERT INTO nationalities (id,name) VALUES (45,'анкалын');
INSERT INTO nationalities (id,name) VALUES (46,'анкальын');
INSERT INTO nationalities (id,name) VALUES (47,'апокваямыл');
INSERT INTO nationalities (id,name) VALUES (48,'апсуа');
INSERT INTO nationalities (id,name) VALUES (49,'апукинцы');
INSERT INTO nationalities (id,name) VALUES (50,'араби');
INSERT INTO nationalities (id,name) VALUES (51,'арабы');
INSERT INTO nationalities (id,name) VALUES (52,'арабы ОАЭ');
INSERT INTO nationalities (id,name) VALUES (53,'арабы среднеазиатские');
INSERT INTO nationalities (id,name) VALUES (54,'аравийцы');
INSERT INTO nationalities (id,name) VALUES (55,'арамеи');
INSERT INTO nationalities (id,name) VALUES (56,'аргын');
INSERT INTO nationalities (id,name) VALUES (57,'армяне');
INSERT INTO nationalities (id,name) VALUES (58,'армяне донские');
INSERT INTO nationalities (id,name) VALUES (59,'армяне крымские');
INSERT INTO nationalities (id,name) VALUES (60,'арнауты');
INSERT INTO nationalities (id,name) VALUES (61,'арчи');
INSERT INTO nationalities (id,name) VALUES (62,'арчиб');
INSERT INTO nationalities (id,name) VALUES (63,'арчинцы');
INSERT INTO nationalities (id,name) VALUES (64,'аршиштиб');
INSERT INTO nationalities (id,name) VALUES (65,'асори');
INSERT INTO nationalities (id,name) VALUES (66,'ассирийцы');
INSERT INTO nationalities (id,name) VALUES (67,'ассурайя');
INSERT INTO nationalities (id,name) VALUES (68,'астраханские татары');
INSERT INTO nationalities (id,name) VALUES (69,'атали');
INSERT INTO nationalities (id,name) VALUES (70,'атурая');
INSERT INTO nationalities (id,name) VALUES (71,'аукштайты');
INSERT INTO nationalities (id,name) VALUES (72,'ауховцы');
INSERT INTO nationalities (id,name) VALUES (73,'афганцы');
INSERT INTO nationalities (id,name) VALUES (74,'ахвалал');
INSERT INTO nationalities (id,name) VALUES (75,'ахвахцы');
INSERT INTO nationalities (id,name) VALUES (76,'ахтинцы');
INSERT INTO nationalities (id,name) VALUES (77,'ашвалъ');
INSERT INTO nationalities (id,name) VALUES (78,'ашватл');
INSERT INTO nationalities (id,name) VALUES (79,'ашкеназ');
INSERT INTO nationalities (id,name) VALUES (80,'ашхаруа');
INSERT INTO nationalities (id,name) VALUES (81,'ашхарцы');
INSERT INTO nationalities (id,name) VALUES (82,'багвалалы');
INSERT INTO nationalities (id,name) VALUES (83,'багвалинцы');
INSERT INTO nationalities (id,name) VALUES (84,'багулав');
INSERT INTO nationalities (id,name) VALUES (85,'багулалы');
INSERT INTO nationalities (id,name) VALUES (86,'баджавидж');
INSERT INTO nationalities (id,name) VALUES (87,'баджуведж');
INSERT INTO nationalities (id,name) VALUES (88,'баджувцы');
INSERT INTO nationalities (id,name) VALUES (89,'баджуйцы');
INSERT INTO nationalities (id,name) VALUES (90,'балкарцы');
INSERT INTO nationalities (id,name) VALUES (91,'балуч');
INSERT INTO nationalities (id,name) VALUES (92,'бани исроил');
INSERT INTO nationalities (id,name) VALUES (93,'бараба');
INSERT INTO nationalities (id,name) VALUES (94,'барабинцы');
INSERT INTO nationalities (id,name) VALUES (95,'баряат');
INSERT INTO nationalities (id,name) VALUES (96,'бахрейнцы');
INSERT INTO nationalities (id,name) VALUES (97,'башкиры');
INSERT INTO nationalities (id,name) VALUES (98,'башкиры-тептяри');
INSERT INTO nationalities (id,name) VALUES (99,'башкорт');
INSERT INTO nationalities (id,name) VALUES (100,'башкурт');
INSERT INTO nationalities (id,name) VALUES (101,'бежитинцы');
INSERT INTO nationalities (id,name) VALUES (102,'бежтинцы');
INSERT INTO nationalities (id,name) VALUES (103,'беларусы');
INSERT INTO nationalities (id,name) VALUES (104,'белорусы');
INSERT INTO nationalities (id,name) VALUES (105,'белуджи');
INSERT INTO nationalities (id,name) VALUES (106,'бенгали');
INSERT INTO nationalities (id,name) VALUES (107,'бенгальцы');
INSERT INTO nationalities (id,name) VALUES (108,'бепся');
INSERT INTO nationalities (id,name) VALUES (109,'берш');
INSERT INTO nationalities (id,name) VALUES (110,'бесермяне');
INSERT INTO nationalities (id,name) VALUES (111,'бесленеевцы (с родным языком адыгейским)');
INSERT INTO nationalities (id,name) VALUES (112,'бесленеевцы (с родным языком кабардино-черкесским)');
INSERT INTO nationalities (id,name) VALUES (113,'бесленеи');
INSERT INTO nationalities (id,name) VALUES (114,'бешермяне');
INSERT INTO nationalities (id,name) VALUES (115,'бжедуги');
INSERT INTO nationalities (id,name) VALUES (116,'бзыбцы');
INSERT INTO nationalities (id,name) VALUES (117,'бойки');
INSERT INTO nationalities (id,name) VALUES (118,'болгары');
INSERT INTO nationalities (id,name) VALUES (119,'большие дэрбэты');
INSERT INTO nationalities (id,name) VALUES (120,'ботлихцы');
INSERT INTO nationalities (id,name) VALUES (121,'бохарлы');
INSERT INTO nationalities (id,name) VALUES (122,'брещуки');
INSERT INTO nationalities (id,name) VALUES (123,'бузавы');
INSERT INTO nationalities (id,name) VALUES (124,'буйхади');
INSERT INTO nationalities (id,name) VALUES (125,'буковинцы');
INSERT INTO nationalities (id,name) VALUES (126,'буряад');
INSERT INTO nationalities (id,name) VALUES (127,'буряты');
INSERT INTO nationalities (id,name) VALUES (128,'бухарские евреи');
INSERT INTO nationalities (id,name) VALUES (129,'бухарцы');
INSERT INTO nationalities (id,name) VALUES (130,'ваду');
INSERT INTO nationalities (id,name) VALUES (131,'вадьякко');
INSERT INTO nationalities (id,name) VALUES (132,'вадьялайн');
INSERT INTO nationalities (id,name) VALUES (133,'венгры');
INSERT INTO nationalities (id,name) VALUES (134,'вепсы');
INSERT INTO nationalities (id,name) VALUES (135,'вепся');
INSERT INTO nationalities (id,name) VALUES (136,'верховинцы');
INSERT INTO nationalities (id,name) VALUES (137,'ветлужские марийцы');
INSERT INTO nationalities (id,name) VALUES (138,'вирьял');
INSERT INTO nationalities (id,name) VALUES (139,'вогулы');
INSERT INTO nationalities (id,name) VALUES (140,'водь');
INSERT INTO nationalities (id,name) VALUES (141,'войкыпал''о');
INSERT INTO nationalities (id,name) VALUES (142,'волохь');
INSERT INTO nationalities (id,name) VALUES (143,'восточные (уральские) марийцы');
INSERT INTO nationalities (id,name) VALUES (144,'вотяки');
INSERT INTO nationalities (id,name) VALUES (145,'воямпольцы');
INSERT INTO nationalities (id,name) VALUES (146,'вудмурт');
INSERT INTO nationalities (id,name) VALUES (147,'вулугуни');
INSERT INTO nationalities (id,name) VALUES (148,'вутла мари');
INSERT INTO nationalities (id,name) VALUES (149,'вьет ньгой');
INSERT INTO nationalities (id,name) VALUES (150,'вьетнамцы');
INSERT INTO nationalities (id,name) VALUES (151,'гагаузы');
INSERT INTO nationalities (id,name) VALUES (152,'гай');
INSERT INTO nationalities (id,name) VALUES (153,'галга');
INSERT INTO nationalities (id,name) VALUES (154,'гантляло');
INSERT INTO nationalities (id,name) VALUES (155,'гванал');
INSERT INTO nationalities (id,name) VALUES (156,'гибдиди');
INSERT INTO nationalities (id,name) VALUES (157,'гиляки');
INSERT INTO nationalities (id,name) VALUES (158,'гинухцы');
INSERT INTO nationalities (id,name) VALUES (159,'годоберинцы');
INSERT INTO nationalities (id,name) VALUES (160,'голендры');
INSERT INTO nationalities (id,name) VALUES (161,'голландцы');
INSERT INTO nationalities (id,name) VALUES (162,'гольды');
INSERT INTO nationalities (id,name) VALUES (163,'горные марийцы');
INSERT INTO nationalities (id,name) VALUES (164,'горские евреи');
INSERT INTO nationalities (id,name) VALUES (165,'греки');
INSERT INTO nationalities (id,name) VALUES (166,'греки-ромеи');
INSERT INTO nationalities (id,name) VALUES (167,'греки-урумы');
INSERT INTO nationalities (id,name) VALUES (168,'греки-эллины');
INSERT INTO nationalities (id,name) VALUES (169,'грекос');
INSERT INTO nationalities (id,name) VALUES (170,'грузинские евреи');
INSERT INTO nationalities (id,name) VALUES (171,'грузины');
INSERT INTO nationalities (id,name) VALUES (172,'гунзал');
INSERT INTO nationalities (id,name) VALUES (173,'гунзибцы');
INSERT INTO nationalities (id,name) VALUES (174,'гурбат');
INSERT INTO nationalities (id,name) VALUES (175,'гуцулы');
INSERT INTO nationalities (id,name) VALUES (176,'гьенози');
INSERT INTO nationalities (id,name) VALUES (177,'гъинухъес');
INSERT INTO nationalities (id,name) VALUES (178,'дагестанские евреи');
INSERT INTO nationalities (id,name) VALUES (179,'даг-чуфут');
INSERT INTO nationalities (id,name) VALUES (180,'дарган');
INSERT INTO nationalities (id,name) VALUES (181,'дарганти');
INSERT INTO nationalities (id,name) VALUES (182,'даргинцы');
INSERT INTO nationalities (id,name) VALUES (183,'дейч');
INSERT INTO nationalities (id,name) VALUES (184,'денг');
INSERT INTO nationalities (id,name) VALUES (185,'дербеты');
INSERT INTO nationalities (id,name) VALUES (186,'деткиль');
INSERT INTO nationalities (id,name) VALUES (187,'дживут бухари');
INSERT INTO nationalities (id,name) VALUES (188,'джуги');
INSERT INTO nationalities (id,name) VALUES (189,'джугут');
INSERT INTO nationalities (id,name) VALUES (190,'джуфут');
INSERT INTO nationalities (id,name) VALUES (191,'джухут');
INSERT INTO nationalities (id,name) VALUES (192,'дигор');
INSERT INTO nationalities (id,name) VALUES (193,'дигорон');
INSERT INTO nationalities (id,name) VALUES (194,'дигорцы');
INSERT INTO nationalities (id,name) VALUES (195,'дидойцы');
INSERT INTO nationalities (id,name) VALUES (196,'дойч');
INSERT INTO nationalities (id,name) VALUES (197,'долган');
INSERT INTO nationalities (id,name) VALUES (198,'долганы');
INSERT INTO nationalities (id,name) VALUES (199,'дом');
INSERT INTO nationalities (id,name) VALUES (200,'донские армяне');
INSERT INTO nationalities (id,name) VALUES (201,'дудки');
INSERT INTO nationalities (id,name) VALUES (202,'дулган');
INSERT INTO nationalities (id,name) VALUES (203,'дунгане');
INSERT INTO nationalities (id,name) VALUES (204,'дэрбеты');
INSERT INTO nationalities (id,name) VALUES (205,'дэрбэты');
INSERT INTO nationalities (id,name) VALUES (206,'большие дэрбэты');
INSERT INTO nationalities (id,name) VALUES (207,'малые дюрбеты');
INSERT INTO nationalities (id,name) VALUES (208,'дянь');
INSERT INTO nationalities (id,name) VALUES (209,'евреи');
INSERT INTO nationalities (id,name) VALUES (210,'евреи бухарские');
INSERT INTO nationalities (id,name) VALUES (211,'евреи горские');
INSERT INTO nationalities (id,name) VALUES (212,'евреи грузинские');
INSERT INTO nationalities (id,name) VALUES (213,'евреи дагестанские');
INSERT INTO nationalities (id,name) VALUES (214,'евреи крымские');
INSERT INTO nationalities (id,name) VALUES (215,'евреи среднеазиатские');
INSERT INTO nationalities (id,name) VALUES (216,'евреи татские');
INSERT INTO nationalities (id,name) VALUES (217,'египтяне');
INSERT INTO nationalities (id,name) VALUES (218,'езды');
INSERT INTO nationalities (id,name) VALUES (219,'езиды');
INSERT INTO nationalities (id,name) VALUES (220,'ёгэн');
INSERT INTO nationalities (id,name) VALUES (221,'жагайбайлы');
INSERT INTO nationalities (id,name) VALUES (222,'жаппас');
INSERT INTO nationalities (id,name) VALUES (223,'жемайты');
INSERT INTO nationalities (id,name) VALUES (224,'заболотные татары');
INSERT INTO nationalities (id,name) VALUES (225,'затундренные крестьяне');
INSERT INTO nationalities (id,name) VALUES (226,'зыряне');
INSERT INTO nationalities (id,name) VALUES (227,'ибдиди');
INSERT INTO nationalities (id,name) VALUES (228,'иври');
INSERT INTO nationalities (id,name) VALUES (229,'идари');
INSERT INTO nationalities (id,name) VALUES (230,'идери');
INSERT INTO nationalities (id,name) VALUES (231,'иди');
INSERT INTO nationalities (id,name) VALUES (232,'иезиды');
INSERT INTO nationalities (id,name) VALUES (233,'ижемцы');
INSERT INTO nationalities (id,name) VALUES (234,'ижора');
INSERT INTO nationalities (id,name) VALUES (235,'ижорцы');
INSERT INTO nationalities (id,name) VALUES (236,'изури');
INSERT INTO nationalities (id,name) VALUES (237,'изьватас');
INSERT INTO nationalities (id,name) VALUES (238,'илийцы');
INSERT INTO nationalities (id,name) VALUES (239,'илкан');
INSERT INTO nationalities (id,name) VALUES (240,'илэ');
INSERT INTO nationalities (id,name) VALUES (241,'имак''лъит');
INSERT INTO nationalities (id,name) VALUES (242,'ингерманландцы');
INSERT INTO nationalities (id,name) VALUES (243,'ингилой');
INSERT INTO nationalities (id,name) VALUES (244,'ингилойцы');
INSERT INTO nationalities (id,name) VALUES (245,'ингрикот');
INSERT INTO nationalities (id,name) VALUES (246,'ингры');
INSERT INTO nationalities (id,name) VALUES (247,'ингуши');
INSERT INTO nationalities (id,name) VALUES (248,'индигирщики');
INSERT INTO nationalities (id,name) VALUES (249,'индийцы хиндиязычные');
INSERT INTO nationalities (id,name) VALUES (250,'инкерилайнен');
INSERT INTO nationalities (id,name) VALUES (251,'инхокваринцы');
INSERT INTO nationalities (id,name) VALUES (252,'иорданцы');
INSERT INTO nationalities (id,name) VALUES (253,'иракцы');
INSERT INTO nationalities (id,name) VALUES (254,'иранцы');
INSERT INTO nationalities (id,name) VALUES (255,'ирон');
INSERT INTO nationalities (id,name) VALUES (256,'иронцы');
INSERT INTO nationalities (id,name) VALUES (257,'испанцы');
INSERT INTO nationalities (id,name) VALUES (258,'исроэл');
INSERT INTO nationalities (id,name) VALUES (259,'итальянцы');
INSERT INTO nationalities (id,name) VALUES (260,'ительмены');
INSERT INTO nationalities (id,name) VALUES (261,'ительмень');
INSERT INTO nationalities (id,name) VALUES (262,'итэнмьи');
INSERT INTO nationalities (id,name) VALUES (263,'иезиды');
INSERT INTO nationalities (id,name) VALUES (264,'йеменцы');
INSERT INTO nationalities (id,name) VALUES (265,'йыхбы');
INSERT INTO nationalities (id,name) VALUES (266,'кабардей');
INSERT INTO nationalities (id,name) VALUES (267,'кабардинцы');
INSERT INTO nationalities (id,name) VALUES (268,'кабган');
INSERT INTO nationalities (id,name) VALUES (269,'казанлы');
INSERT INTO nationalities (id,name) VALUES (270,'казанские татары');
INSERT INTO nationalities (id,name) VALUES (271,'казахи');
INSERT INTO nationalities (id,name) VALUES (272,'казахи степские');
INSERT INTO nationalities (id,name) VALUES (273,'казахи туратинские');
INSERT INTO nationalities (id,name) VALUES (274,'кайтаги');
INSERT INTO nationalities (id,name) VALUES (275,'каитагцы');
INSERT INTO nationalities (id,name) VALUES (276,'калмаки');
INSERT INTO nationalities (id,name) VALUES (277,'калмыки');
INSERT INTO nationalities (id,name) VALUES (278,'калпак');
INSERT INTO nationalities (id,name) VALUES (279,'каменцы');
INSERT INTO nationalities (id,name) VALUES (280,'каменщики');
INSERT INTO nationalities (id,name) VALUES (281,'камчадалы (с родным языком ительменским)');
INSERT INTO nationalities (id,name) VALUES (282,'камчадалы (с родным языком русским)');
INSERT INTO nationalities (id,name) VALUES (283,'канинские поморы');
INSERT INTO nationalities (id,name) VALUES (284,'кантага ях');
INSERT INTO nationalities (id,name) VALUES (285,'капучины');
INSERT INTO nationalities (id,name) VALUES (286,'карагасы');
INSERT INTO nationalities (id,name) VALUES (287,'карагасы томские');
INSERT INTO nationalities (id,name) VALUES (288,'карагаши');
INSERT INTO nationalities (id,name) VALUES (289,'карагинцы');
INSERT INTO nationalities (id,name) VALUES (290,'караимы');
INSERT INTO nationalities (id,name) VALUES (291,'карай');
INSERT INTO nationalities (id,name) VALUES (292,'кара-кайтаги');
INSERT INTO nationalities (id,name) VALUES (293,'каракалпаки');
INSERT INTO nationalities (id,name) VALUES (294,'караногайцы');
INSERT INTO nationalities (id,name) VALUES (295,'каран''ыныльо');
INSERT INTO nationalities (id,name) VALUES (296,'каратаи');
INSERT INTO nationalities (id,name) VALUES (297,'каратинцы');
INSERT INTO nationalities (id,name) VALUES (298,'карачаевцы');
INSERT INTO nationalities (id,name) VALUES (299,'карачай');
INSERT INTO nationalities (id,name) VALUES (300,'карачайлыла (карачайлы)');
INSERT INTO nationalities (id,name) VALUES (301,'карелы');
INSERT INTO nationalities (id,name) VALUES (302,'карийские (нукратские) татары');
INSERT INTO nationalities (id,name) VALUES (303,'каролпак');
INSERT INTO nationalities (id,name) VALUES (304,'карпатороссы');
INSERT INTO nationalities (id,name) VALUES (305,'картвели');
INSERT INTO nationalities (id,name) VALUES (306,'карымы');
INSERT INTO nationalities (id,name) VALUES (307,'карьяла');
INSERT INTO nationalities (id,name) VALUES (308,'карьялайзет');
INSERT INTO nationalities (id,name) VALUES (309,'карьялани');
INSERT INTO nationalities (id,name) VALUES (310,'карьяляйн');
INSERT INTO nationalities (id,name) VALUES (311,'касимовские татары');
INSERT INTO nationalities (id,name) VALUES (312,'катарцы');
INSERT INTO nationalities (id,name) VALUES (313,'качинцы');
INSERT INTO nationalities (id,name) VALUES (314,'кашгарцы');
INSERT INTO nationalities (id,name) VALUES (315,'кванадинцы');
INSERT INTO nationalities (id,name) VALUES (316,'кванадлетцы');
INSERT INTO nationalities (id,name) VALUES (317,'кваннал');
INSERT INTO nationalities (id,name) VALUES (318,'кемгуи');
INSERT INTO nationalities (id,name) VALUES (319,'керей');
INSERT INTO nationalities (id,name) VALUES (320,'кереки');
INSERT INTO nationalities (id,name) VALUES (321,'кержаки');
INSERT INTO nationalities (id,name) VALUES (322,'кето');
INSERT INTO nationalities (id,name) VALUES (323,'кеты');
INSERT INTO nationalities (id,name) VALUES (324,'киргизы');
INSERT INTO nationalities (id,name) VALUES (325,'кирди');
INSERT INTO nationalities (id,name) VALUES (326,'китайцы');
INSERT INTO nationalities (id,name) VALUES (327,'кожла марий');
INSERT INTO nationalities (id,name) VALUES (328,'койбалы');
INSERT INTO nationalities (id,name) VALUES (329,'колымские');
INSERT INTO nationalities (id,name) VALUES (330,'колымчане');
INSERT INTO nationalities (id,name) VALUES (331,'коми (с родным языком коми)');
INSERT INTO nationalities (id,name) VALUES (332,'коми (с родным языком коми-пермяцким)');
INSERT INTO nationalities (id,name) VALUES (333,'коми войтыр');
INSERT INTO nationalities (id,name) VALUES (334,'коми йоз');
INSERT INTO nationalities (id,name) VALUES (335,'коми морт (с родным языком коми)');
INSERT INTO nationalities (id,name) VALUES (336,'коми морт (с родным языком коми-пермяцким)');
INSERT INTO nationalities (id,name) VALUES (337,'коми отир');
INSERT INTO nationalities (id,name) VALUES (338,'коми-ижемцы');
INSERT INTO nationalities (id,name) VALUES (339,'коми-зыряне');
INSERT INTO nationalities (id,name) VALUES (340,'коми-пермяки');
INSERT INTO nationalities (id,name) VALUES (341,'корейцы');
INSERT INTO nationalities (id,name) VALUES (342,'коре сарам');
INSERT INTO nationalities (id,name) VALUES (343,'коряки');
INSERT INTO nationalities (id,name) VALUES (344,'крестьяне затундренные');
INSERT INTO nationalities (id,name) VALUES (345,'крещенцы');
INSERT INTO nationalities (id,name) VALUES (346,'крещеные');
INSERT INTO nationalities (id,name) VALUES (347,'крымские армяне');
INSERT INTO nationalities (id,name) VALUES (348,'крымские евреи');
INSERT INTO nationalities (id,name) VALUES (349,'крымские ногаи');
INSERT INTO nationalities (id,name) VALUES (350,'крымские татары');
INSERT INTO nationalities (id,name) VALUES (351,'крымчаки');
INSERT INTO nationalities (id,name) VALUES (352,'кряшены');
INSERT INTO nationalities (id,name) VALUES (353,'куаннал');
INSERT INTO nationalities (id,name) VALUES (354,'кубанды');
INSERT INTO nationalities (id,name) VALUES (355,'кубачинцы');
INSERT INTO nationalities (id,name) VALUES (356,'кубинцы');
INSERT INTO nationalities (id,name) VALUES (357,'кувейтцы');
INSERT INTO nationalities (id,name) VALUES (358,'кудайраг');
INSERT INTO nationalities (id,name) VALUES (359,'кударцы');
INSERT INTO nationalities (id,name) VALUES (360,'кумандинцы');
INSERT INTO nationalities (id,name) VALUES (361,'куманды');
INSERT INTO nationalities (id,name) VALUES (362,'кумук');
INSERT INTO nationalities (id,name) VALUES (363,'кумыки');
INSERT INTO nationalities (id,name) VALUES (364,'кундровцы');
INSERT INTO nationalities (id,name) VALUES (365,'курд');
INSERT INTO nationalities (id,name) VALUES (366,'курдакско-саргатские татары');
INSERT INTO nationalities (id,name) VALUES (367,'курды');
INSERT INTO nationalities (id,name) VALUES (368,'курмандж');
INSERT INTO nationalities (id,name) VALUES (369,'курык марий');
INSERT INTO nationalities (id,name) VALUES (370,'кърым татарлар');
INSERT INTO nationalities (id,name) VALUES (371,'кызыл');
INSERT INTO nationalities (id,name) VALUES (372,'кызыльцы');
INSERT INTO nationalities (id,name) VALUES (373,'кыпчак (с родным языком алтайским)');
INSERT INTO nationalities (id,name) VALUES (374,'кыпчак (с родным языком казахским)');
INSERT INTO nationalities (id,name) VALUES (375,'кыргыз');
INSERT INTO nationalities (id,name) VALUES (376,'кюрегу');
INSERT INTO nationalities (id,name) VALUES (377,'кюринцы');
INSERT INTO nationalities (id,name) VALUES (378,'лазы');
INSERT INTO nationalities (id,name) VALUES (379,'лак');
INSERT INTO nationalities (id,name) VALUES (380,'лаки');
INSERT INTO nationalities (id,name) VALUES (381,'лаккучу');
INSERT INTO nationalities (id,name) VALUES (382,'лакцы');
INSERT INTO nationalities (id,name) VALUES (383,'ламут');
INSERT INTO nationalities (id,name) VALUES (384,'ламут-наматкан');
INSERT INTO nationalities (id,name) VALUES (385,'лао хуйхуй');
INSERT INTO nationalities (id,name) VALUES (386,'лаппи');
INSERT INTO nationalities (id,name) VALUES (387,'латвиетис');
INSERT INTO nationalities (id,name) VALUES (388,'латвиеши');
INSERT INTO nationalities (id,name) VALUES (389,'латгальцы');
INSERT INTO nationalities (id,name) VALUES (390,'латгалиетис');
INSERT INTO nationalities (id,name) VALUES (391,'латыши');
INSERT INTO nationalities (id,name) VALUES (392,'лезги');
INSERT INTO nationalities (id,name) VALUES (393,'лезгины');
INSERT INTO nationalities (id,name) VALUES (394,'лезгияр');
INSERT INTO nationalities (id,name) VALUES (395,'лемки');
INSERT INTO nationalities (id,name) VALUES (396,'ленские старожилы');
INSERT INTO nationalities (id,name) VALUES (397,'лесные марийцы');
INSERT INTO nationalities (id,name) VALUES (398,'летувис');
INSERT INTO nationalities (id,name) VALUES (399,'летувник');
INSERT INTO nationalities (id,name) VALUES (400,'летувяй');
INSERT INTO nationalities (id,name) VALUES (401,'ливанцы');
INSERT INTO nationalities (id,name) VALUES (402,'ливвикёй');
INSERT INTO nationalities (id,name) VALUES (403,'ливвики');
INSERT INTO nationalities (id,name) VALUES (404,'ливгиляйне');
INSERT INTO nationalities (id,name) VALUES (405,'ливийцы');
INSERT INTO nationalities (id,name) VALUES (406,'литвин (с родным языком белорусским)');
INSERT INTO nationalities (id,name) VALUES (407,'литвин (с родным языком литовским)');
INSERT INTO nationalities (id,name) VALUES (408,'литвяк (с родным языком белорусским)');
INSERT INTO nationalities (id,name) VALUES (409,'литвяк (с родным языком литовским)');
INSERT INTO nationalities (id,name) VALUES (410,'литовцы');
INSERT INTO nationalities (id,name) VALUES (411,'лопари');
INSERT INTO nationalities (id,name) VALUES (412,'лугово-восточные марийцы');
INSERT INTO nationalities (id,name) VALUES (413,'луговые марийцы');
INSERT INTO nationalities (id,name) VALUES (414,'луораветлан');
INSERT INTO nationalities (id,name) VALUES (415,'лыгъоравэтлъан');
INSERT INTO nationalities (id,name) VALUES (416,'лыгъоравэтлят');
INSERT INTO nationalities (id,name) VALUES (417,'людики');
INSERT INTO nationalities (id,name) VALUES (418,'людиникат');
INSERT INTO nationalities (id,name) VALUES (419,'люли');
INSERT INTO nationalities (id,name) VALUES (420,'лююдикёй');
INSERT INTO nationalities (id,name) VALUES (421,'лююдилайне (с родным языком вепсским)');
INSERT INTO nationalities (id,name) VALUES (422,'лююдилайне (с родным языком карельским)');
INSERT INTO nationalities (id,name) VALUES (423,'маарулал');
INSERT INTO nationalities (id,name) VALUES (424,'мавританцы');
INSERT INTO nationalities (id,name) VALUES (425,'мавры');
INSERT INTO nationalities (id,name) VALUES (426,'маду');
INSERT INTO nationalities (id,name) VALUES (427,'мадьяр');
INSERT INTO nationalities (id,name) VALUES (428,'мазанг');
INSERT INTO nationalities (id,name) VALUES (429,'майминцы');
INSERT INTO nationalities (id,name) VALUES (430,'малкарцы');
INSERT INTO nationalities (id,name) VALUES (431,'малкъарлыла (малкъарлы)');
INSERT INTO nationalities (id,name) VALUES (432,'малые дэрбэты');
INSERT INTO nationalities (id,name) VALUES (433,'мамхеги');
INSERT INTO nationalities (id,name) VALUES (434,'мангуны');
INSERT INTO nationalities (id,name) VALUES (435,'манегры');
INSERT INTO nationalities (id,name) VALUES (436,'манси');
INSERT INTO nationalities (id,name) VALUES (437,'мар');
INSERT INTO nationalities (id,name) VALUES (438,'маргали');
INSERT INTO nationalities (id,name) VALUES (439,'мари');
INSERT INTO nationalities (id,name) VALUES (440,'марий');
INSERT INTO nationalities (id,name) VALUES (441,'марийцы');
INSERT INTO nationalities (id,name) VALUES (442,'марийцы ветлужские');
INSERT INTO nationalities (id,name) VALUES (443,'марийцы восточные (уральские)');
INSERT INTO nationalities (id,name) VALUES (444,'марийцы горные');
INSERT INTO nationalities (id,name) VALUES (445,'марийцы лесные');
INSERT INTO nationalities (id,name) VALUES (446,'марийцы лугово-восточные');
INSERT INTO nationalities (id,name) VALUES (447,'марийцы луговые');
INSERT INTO nationalities (id,name) VALUES (448,'марийцы уральские (восточные)');
INSERT INTO nationalities (id,name) VALUES (449,'марковцы');
INSERT INTO nationalities (id,name) VALUES (450,'марокканцы');
INSERT INTO nationalities (id,name) VALUES (451,'махмеги');
INSERT INTO nationalities (id,name) VALUES (452,'махмеговцы');
INSERT INTO nationalities (id,name) VALUES (453,'мегрелы');
INSERT INTO nationalities (id,name) VALUES (454,'мегьебор');
INSERT INTO nationalities (id,name) VALUES (455,'мезенцы');
INSERT INTO nationalities (id,name) VALUES (456,'меннонитен');
INSERT INTO nationalities (id,name) VALUES (457,'меннониты');
INSERT INTO nationalities (id,name) VALUES (458,'меньдси');
INSERT INTO nationalities (id,name) VALUES (459,'месхетинцы-турки');
INSERT INTO nationalities (id,name) VALUES (460,'мещеряки');
INSERT INTO nationalities (id,name) VALUES (461,'мижерь');
INSERT INTO nationalities (id,name) VALUES (462,'мингрелы');
INSERT INTO nationalities (id,name) VALUES (463,'мишари');
INSERT INTO nationalities (id,name) VALUES (464,'мишэр');
INSERT INTO nationalities (id,name) VALUES (465,'моансь');
INSERT INTO nationalities (id,name) VALUES (466,'могади');
INSERT INTO nationalities (id,name) VALUES (467,'мокша');
INSERT INTO nationalities (id,name) VALUES (468,'молдаване');
INSERT INTO nationalities (id,name) VALUES (469,'молдовень');
INSERT INTO nationalities (id,name) VALUES (470,'монголы');
INSERT INTO nationalities (id,name) VALUES (471,'мораване');
INSERT INTO nationalities (id,name) VALUES (472,'мордва');
INSERT INTO nationalities (id,name) VALUES (473,'мордва-мокша');
INSERT INTO nationalities (id,name) VALUES (474,'мордва-эрзя');
INSERT INTO nationalities (id,name) VALUES (475,'мордвины');
INSERT INTO nationalities (id,name) VALUES (476,'мордовцы');
INSERT INTO nationalities (id,name) VALUES (477,'мугат');
INSERT INTO nationalities (id,name) VALUES (478,'мультони');
INSERT INTO nationalities (id,name) VALUES (479,'мурчен');
INSERT INTO nationalities (id,name) VALUES (480,'мых абдыр');
INSERT INTO nationalities (id,name) VALUES (481,'мэнэ');
INSERT INTO nationalities (id,name) VALUES (482,'мюхадар');
INSERT INTO nationalities (id,name) VALUES (483,'на бэйенин');
INSERT INTO nationalities (id,name) VALUES (484,'навукагмит');
INSERT INTO nationalities (id,name) VALUES (485,'нагайбаки');
INSERT INTO nationalities (id,name) VALUES (486,'нагайбэклэр');
INSERT INTO nationalities (id,name) VALUES (487,'найман (с родным языком алтайским)');
INSERT INTO nationalities (id,name) VALUES (488,'найман (с родным языком казахским)');
INSERT INTO nationalities (id,name) VALUES (489,'нанай');
INSERT INTO nationalities (id,name) VALUES (490,'нанайцы');
INSERT INTO nationalities (id,name) VALUES (491,'нани (с родным языком нанайским)');
INSERT INTO nationalities (id,name) VALUES (492,'нани (с родным языком ороч-ским)');
INSERT INTO nationalities (id,name) VALUES (493,'нани (с родным языком ульч-ским)');
INSERT INTO nationalities (id,name) VALUES (494,'нахада');
INSERT INTO nationalities (id,name) VALUES (495,'нганасаны');
INSERT INTO nationalities (id,name) VALUES (496,'не');
INSERT INTO nationalities (id,name) VALUES (497,'негды');
INSERT INTO nationalities (id,name) VALUES (498,'негидальцы');
INSERT INTO nationalities (id,name) VALUES (499,'немцы');
INSERT INTO nationalities (id,name) VALUES (500,'немцы-меннониты');
INSERT INTO nationalities (id,name) VALUES (501,'ненач');
INSERT INTO nationalities (id,name) VALUES (502,'ненцы');
INSERT INTO nationalities (id,name) VALUES (503,'ненэй ненэц');
INSERT INTO nationalities (id,name) VALUES (504,'ненэйне');
INSERT INTO nationalities (id,name) VALUES (505,'ненэчэ');
INSERT INTO nationalities (id,name) VALUES (506,'нещанг');
INSERT INTO nationalities (id,name) VALUES (507,'нибах');
INSERT INTO nationalities (id,name) VALUES (508,'нивах');
INSERT INTO nationalities (id,name) VALUES (509,'нивух');
INSERT INTO nationalities (id,name) VALUES (510,'нивхгу');
INSERT INTO nationalities (id,name) VALUES (511,'нивхи');
INSERT INTO nationalities (id,name) VALUES (512,'нихондзин');
INSERT INTO nationalities (id,name) VALUES (513,'ногаи крымские');
INSERT INTO nationalities (id,name) VALUES (514,'ногай (с родным языком казахским)');
INSERT INTO nationalities (id,name) VALUES (515,'ногай (с родным языком ногайским)');
INSERT INTO nationalities (id,name) VALUES (516,'ногай-карагаш');
INSERT INTO nationalities (id,name) VALUES (517,'ногайцы');
INSERT INTO nationalities (id,name) VALUES (518,'нохчий');
INSERT INTO nationalities (id,name) VALUES (519,'нугай татар');
INSERT INTO nationalities (id,name) VALUES (520,'нукратские (карийские) татары');
INSERT INTO nationalities (id,name) VALUES (521,'нымыланы');
INSERT INTO nationalities (id,name) VALUES (522,'нымылгын');
INSERT INTO nationalities (id,name) VALUES (523,'ньигвнгун');
INSERT INTO nationalities (id,name) VALUES (524,'ня');
INSERT INTO nationalities (id,name) VALUES (525,'нясихагил');
INSERT INTO nationalities (id,name) VALUES (526,'обские старожилы');
INSERT INTO nationalities (id,name) VALUES (527,'овен');
INSERT INTO nationalities (id,name) VALUES (528,'овон');
INSERT INTO nationalities (id,name) VALUES (529,'одморт');
INSERT INTO nationalities (id,name) VALUES (530,'одмурт');
INSERT INTO nationalities (id,name) VALUES (531,'озбак');
INSERT INTO nationalities (id,name) VALUES (532,'озбек');
INSERT INTO nationalities (id,name) VALUES (533,'ойраты');
INSERT INTO nationalities (id,name) VALUES (534,'окморт');
INSERT INTO nationalities (id,name) VALUES (535,'олёты');
INSERT INTO nationalities (id,name) VALUES (536,'олык марий');
INSERT INTO nationalities (id,name) VALUES (537,'олюторцы');
INSERT INTO nationalities (id,name) VALUES (538,'оманцы');
INSERT INTO nationalities (id,name) VALUES (539,'омоки');
INSERT INTO nationalities (id,name) VALUES (540,'оре куманды');
INSERT INTO nationalities (id,name) VALUES (541,'ороки (ульта)');
INSERT INTO nationalities (id,name) VALUES (542,'ороч (с родным языком орочским)');
INSERT INTO nationalities (id,name) VALUES (543,'ороч (с родным языком ульта)');
INSERT INTO nationalities (id,name) VALUES (544,'ороч (с родным языком эвенским)');
INSERT INTO nationalities (id,name) VALUES (545,'орочель');
INSERT INTO nationalities (id,name) VALUES (546,'орочёл');
INSERT INTO nationalities (id,name) VALUES (547,'орочён (с родным языком орочским)');
INSERT INTO nationalities (id,name) VALUES (548,'орочён (с родным языком ульта)');
INSERT INTO nationalities (id,name) VALUES (549,'орочён (с родным языком эвенкийским)');
INSERT INTO nationalities (id,name) VALUES (550,'орочён (с родным языком эвенским)');
INSERT INTO nationalities (id,name) VALUES (551,'орочи');
INSERT INTO nationalities (id,name) VALUES (552,'орочисэл');
INSERT INTO nationalities (id,name) VALUES (553,'орум');
INSERT INTO nationalities (id,name) VALUES (554,'осетины');
INSERT INTO nationalities (id,name) VALUES (555,'осетины-дигорцы');
INSERT INTO nationalities (id,name) VALUES (556,'осетины-иронцы');
INSERT INTO nationalities (id,name) VALUES (557,'османы');
INSERT INTO nationalities (id,name) VALUES (558,'остяки (с родным языком кетским)');
INSERT INTO nationalities (id,name) VALUES (559,'остяки (с родным языком мансийским)');
INSERT INTO nationalities (id,name) VALUES (560,'остяки (с родным языком селькупским)');
INSERT INTO nationalities (id,name) VALUES (561,'остяки (с родным языком хантыйским)');
INSERT INTO nationalities (id,name) VALUES (562,'палестинцы (с родным языком арабским)');
INSERT INTO nationalities (id,name) VALUES (563,'параба');
INSERT INTO nationalities (id,name) VALUES (564,'парс');
INSERT INTO nationalities (id,name) VALUES (565,'патаны');
INSERT INTO nationalities (id,name) VALUES (566,'пахтуны');
INSERT INTO nationalities (id,name) VALUES (567,'пашенные');
INSERT INTO nationalities (id,name) VALUES (568,'пермяки');
INSERT INTO nationalities (id,name) VALUES (569,'персы');
INSERT INTO nationalities (id,name) VALUES (570,'полуверцы');
INSERT INTO nationalities (id,name) VALUES (571,'поляки');
INSERT INTO nationalities (id,name) VALUES (572,'поляци');
INSERT INTO nationalities (id,name) VALUES (573,'поморы');
INSERT INTO nationalities (id,name) VALUES (574,'поморы канинские');
INSERT INTO nationalities (id,name) VALUES (575,'понтиос');
INSERT INTO nationalities (id,name) VALUES (576,'португальцы');
INSERT INTO nationalities (id,name) VALUES (577,'походчане');
INSERT INTO nationalities (id,name) VALUES (578,'пуштуны');
INSERT INTO nationalities (id,name) VALUES (579,'пэ-бай');
INSERT INTO nationalities (id,name) VALUES (580,'пян хасова');
INSERT INTO nationalities (id,name) VALUES (581,'ром');
INSERT INTO nationalities (id,name) VALUES (582,'рома');
INSERT INTO nationalities (id,name) VALUES (583,'ромеи');
INSERT INTO nationalities (id,name) VALUES (584,'ромеос');
INSERT INTO nationalities (id,name) VALUES (585,'ромеюс');
INSERT INTO nationalities (id,name) VALUES (586,'ромынь');
INSERT INTO nationalities (id,name) VALUES (587,'рум');
INSERT INTO nationalities (id,name) VALUES (588,'румей');
INSERT INTO nationalities (id,name) VALUES (589,'румыны');
INSERT INTO nationalities (id,name) VALUES (590,'русины');
INSERT INTO nationalities (id,name) VALUES (591,'русские');
INSERT INTO nationalities (id,name) VALUES (592,'русско-устьинцы');
INSERT INTO nationalities (id,name) VALUES (593,'рутул');
INSERT INTO nationalities (id,name) VALUES (594,'рутульцы');
INSERT INTO nationalities (id,name) VALUES (595,'рухни рушанцы');
INSERT INTO nationalities (id,name) VALUES (596,'рушони');
INSERT INTO nationalities (id,name) VALUES (597,'рыхен');
INSERT INTO nationalities (id,name) VALUES (598,'саами');
INSERT INTO nationalities (id,name) VALUES (599,'саамы');
INSERT INTO nationalities (id,name) VALUES (600,'савакот');
INSERT INTO nationalities (id,name) VALUES (601,'сагай');
INSERT INTO nationalities (id,name) VALUES (602,'сагайцы');
INSERT INTO nationalities (id,name) VALUES (603,'сартулы');
INSERT INTO nationalities (id,name) VALUES (604,'сасигнан');
INSERT INTO nationalities (id,name) VALUES (605,'саудовцы');
INSERT INTO nationalities (id,name) VALUES (606,'саха (с родным языком долганским)');
INSERT INTO nationalities (id,name) VALUES (607,'саха (с родным языком якутским)');
INSERT INTO nationalities (id,name) VALUES (608,'сваны');
INSERT INTO nationalities (id,name) VALUES (609,'селькупы');
INSERT INTO nationalities (id,name) VALUES (610,'семейские');
INSERT INTO nationalities (id,name) VALUES (611,'сербы');
INSERT INTO nationalities (id,name) VALUES (612,'сето');
INSERT INTO nationalities (id,name) VALUES (613,'сету');
INSERT INTO nationalities (id,name) VALUES (614,'сибир татарлар');
INSERT INTO nationalities (id,name) VALUES (615,'сибирские татары');
INSERT INTO nationalities (id,name) VALUES (616,'сиренигмит');
INSERT INTO nationalities (id,name) VALUES (617,'сирийцы');
INSERT INTO nationalities (id,name) VALUES (618,'словаки');
INSERT INTO nationalities (id,name) VALUES (619,'сойоны');
INSERT INTO nationalities (id,name) VALUES (620,'сойоты (с родным языком бурятским)');
INSERT INTO nationalities (id,name) VALUES (621,'сойоты (с родным языком тувинским)');
INSERT INTO nationalities (id,name) VALUES (622,'селькуп');
INSERT INTO nationalities (id,name) VALUES (623,'сомату');
INSERT INTO nationalities (id,name) VALUES (624,'среднеазиатские арабы');
INSERT INTO nationalities (id,name) VALUES (625,'среднеазиатские евреи');
INSERT INTO nationalities (id,name) VALUES (626,'среднеазиатские цыгане');
INSERT INTO nationalities (id,name) VALUES (627,'старожилы ленские');
INSERT INTO nationalities (id,name) VALUES (628,'старожилы обские');
INSERT INTO nationalities (id,name) VALUES (629,'степские казахи');
INSERT INTO nationalities (id,name) VALUES (630,'суданцы');
INSERT INTO nationalities (id,name) VALUES (631,'суомалайсет');
INSERT INTO nationalities (id,name) VALUES (632,'суоми');
INSERT INTO nationalities (id,name) VALUES (633,'сурайя');
INSERT INTO nationalities (id,name) VALUES (634,'суссе кум');
INSERT INTO nationalities (id,name) VALUES (635,'сэрвы');
INSERT INTO nationalities (id,name) VALUES (636,'табасаран');
INSERT INTO nationalities (id,name) VALUES (637,'табасаранцы');
INSERT INTO nationalities (id,name) VALUES (638,'табасараны');
INSERT INTO nationalities (id,name) VALUES (639,'табын');
INSERT INTO nationalities (id,name) VALUES (640,'тавгийцы');
INSERT INTO nationalities (id,name) VALUES (641,'тавоктарош');
INSERT INTO nationalities (id,name) VALUES (642,'тадар');
INSERT INTO nationalities (id,name) VALUES (643,'тадар-кижи (с родным языком кумандинским)');
INSERT INTO nationalities (id,name) VALUES (644,'тадар-кижи (с родным языком телеутским)');
INSERT INTO nationalities (id,name) VALUES (645,'тадар-кижи (с родным языком хакасским)');
INSERT INTO nationalities (id,name) VALUES (646,'тадар-кижи (с родным языком шорским)');
INSERT INTO nationalities (id,name) VALUES (647,'таджики');
INSERT INTO nationalities (id,name) VALUES (648,'тазы');
INSERT INTO nationalities (id,name) VALUES (649,'талыши');
INSERT INTO nationalities (id,name) VALUES (650,'талышон');
INSERT INTO nationalities (id,name) VALUES (651,'тама');
INSERT INTO nationalities (id,name) VALUES (652,'таланта');
INSERT INTO nationalities (id,name) VALUES (653,'таранчи');
INSERT INTO nationalities (id,name) VALUES (654,'тарлик');
INSERT INTO nationalities (id,name) VALUES (655,'тарские татары');
INSERT INTO nationalities (id,name) VALUES (656,'тат (с родным языком крым-скотатарским)');
INSERT INTO nationalities (id,name) VALUES (657,'тат (с родным языком татским)');
INSERT INTO nationalities (id,name) VALUES (658,'татар');
INSERT INTO nationalities (id,name) VALUES (659,'татары');
INSERT INTO nationalities (id,name) VALUES (660,'татары алабугатские');
INSERT INTO nationalities (id,name) VALUES (661,'татары астраханские');
INSERT INTO nationalities (id,name) VALUES (662,'татары заболотные');
INSERT INTO nationalities (id,name) VALUES (663,'татары казанские');
INSERT INTO nationalities (id,name) VALUES (664,'татары карийские (нукратские)');
INSERT INTO nationalities (id,name) VALUES (665,'татары касимовские');
INSERT INTO nationalities (id,name) VALUES (666,'татары крымские');
INSERT INTO nationalities (id,name) VALUES (667,'татары курдакско-саргатские');
INSERT INTO nationalities (id,name) VALUES (668,'татары нукратские (каринские)');
INSERT INTO nationalities (id,name) VALUES (669,'татары сибирские');
INSERT INTO nationalities (id,name) VALUES (670,'татары тарские');
INSERT INTO nationalities (id,name) VALUES (671,'татары тевризские');
INSERT INTO nationalities (id,name) VALUES (672,'татары-тептяри');
INSERT INTO nationalities (id,name) VALUES (673,'татары тобольские');
INSERT INTO nationalities (id,name) VALUES (674,'татары тюменско-тюринские');
INSERT INTO nationalities (id,name) VALUES (675,'татары чулымские');
INSERT INTO nationalities (id,name) VALUES (676,'татары юртовские');
INSERT INTO nationalities (id,name) VALUES (677,'татары ясколбинские');
INSERT INTO nationalities (id,name) VALUES (678,'татские евреи');
INSERT INTO nationalities (id,name) VALUES (679,'таты-азербайджанцы');
INSERT INTO nationalities (id,name) VALUES (680,'таты-иудаисты');
INSERT INTO nationalities (id,name) VALUES (681,'таты-мусульмане');
INSERT INTO nationalities (id,name) VALUES (682,'таулу');
INSERT INTO nationalities (id,name) VALUES (683,'тевризские татары');
INSERT INTO nationalities (id,name) VALUES (684,'теленгиты');
INSERT INTO nationalities (id,name) VALUES (685,'телесы');
INSERT INTO nationalities (id,name) VALUES (686,'телеуты');
INSERT INTO nationalities (id,name) VALUES (687,'темиргоевцы');
INSERT INTO nationalities (id,name) VALUES (688,'тептяри (с родным языком башкирским)');
INSERT INTO nationalities (id,name) VALUES (689,'тептяри (с родным языком татарским)');
INSERT INTO nationalities (id,name) VALUES (690,'тептяри-башкиры');
INSERT INTO nationalities (id,name) VALUES (691,'тептяри-татары');
INSERT INTO nationalities (id,name) VALUES (692,'терюхане');
INSERT INTO nationalities (id,name) VALUES (693,'тиндалы');
INSERT INTO nationalities (id,name) VALUES (694,'тиндии');
INSERT INTO nationalities (id,name) VALUES (695,'тиндинцы');
INSERT INTO nationalities (id,name) VALUES (696,'тлибишинцы');
INSERT INTO nationalities (id,name) VALUES (697,'тлиссинцы');
INSERT INTO nationalities (id,name) VALUES (698,'тоболик');
INSERT INTO nationalities (id,name) VALUES (699,'тобольские');
INSERT INTO nationalities (id,name) VALUES (700,'татары');
INSERT INTO nationalities (id,name) VALUES (701,'тоджик');
INSERT INTO nationalities (id,name) VALUES (702,'тоджинцы');
INSERT INTO nationalities (id,name) VALUES (703,'томские карагасы');
INSERT INTO nationalities (id,name) VALUES (704,'тонгус');
INSERT INTO nationalities (id,name) VALUES (705,'торгоуты');
INSERT INTO nationalities (id,name) VALUES (706,'торгуты');
INSERT INTO nationalities (id,name) VALUES (707,'торкара');
INSERT INTO nationalities (id,name) VALUES (708,'тофа');
INSERT INTO nationalities (id,name) VALUES (709,'тофалары');
INSERT INTO nationalities (id,name) VALUES (710,'трухмены');
INSERT INTO nationalities (id,name) VALUES (711,'туалаг');
INSERT INTO nationalities (id,name) VALUES (712,'туальцы');
INSERT INTO nationalities (id,name) VALUES (713,'туба');
INSERT INTO nationalities (id,name) VALUES (714,'туба-кижи');
INSERT INTO nationalities (id,name) VALUES (715,'тубалары');
INSERT INTO nationalities (id,name) VALUES (716,'тубере куманды');
INSERT INTO nationalities (id,name) VALUES (717,'тува');
INSERT INTO nationalities (id,name) VALUES (718,'тувинцы');
INSERT INTO nationalities (id,name) VALUES (719,'тувинцы-тоджинцы');
INSERT INTO nationalities (id,name) VALUES (720,'туга');
INSERT INTO nationalities (id,name) VALUES (721,'тумал');
INSERT INTO nationalities (id,name) VALUES (722,'тунгусы (с родным языком эвенкийским)');
INSERT INTO nationalities (id,name) VALUES (723,'тунгусы (с родным языком эвенским)');
INSERT INTO nationalities (id,name) VALUES (724,'тунисцы');
INSERT INTO nationalities (id,name) VALUES (725,'тураминцы');
INSERT INTO nationalities (id,name) VALUES (726,'туратинские казахи');
INSERT INTO nationalities (id,name) VALUES (727,'тургэхал');
INSERT INTO nationalities (id,name) VALUES (728,'турки');
INSERT INTO nationalities (id,name) VALUES (729,'турки-батумцы');
INSERT INTO nationalities (id,name) VALUES (730,'турки-месхетинцы');
INSERT INTO nationalities (id,name) VALUES (731,'турки-османы');
INSERT INTO nationalities (id,name) VALUES (732,'турки-сухумцы');
INSERT INTO nationalities (id,name) VALUES (733,'туркмены');
INSERT INTO nationalities (id,name) VALUES (734,'туха');
INSERT INTO nationalities (id,name) VALUES (735,'тыва');
INSERT INTO nationalities (id,name) VALUES (736,'тыва-кижи');
INSERT INTO nationalities (id,name) VALUES (737,'тюменско-тюринские татары');
INSERT INTO nationalities (id,name) VALUES (738,'тюрк (с родным языком азербайджанским)');
INSERT INTO nationalities (id,name) VALUES (739,'тюрк (с родным языком турецким)');
INSERT INTO nationalities (id,name) VALUES (740,'тюрк (с родным языком туркменским)');
INSERT INTO nationalities (id,name) VALUES (741,'тюрк (с родным языком узбекским)');
INSERT INTO nationalities (id,name) VALUES (742,'тюрки чулымские');
INSERT INTO nationalities (id,name) VALUES (743,'уак');
INSERT INTO nationalities (id,name) VALUES (744,'угбуган');
INSERT INTO nationalities (id,name) VALUES (745,'угбуганти');
INSERT INTO nationalities (id,name) VALUES (746,'уди');
INSERT INTO nationalities (id,name) VALUES (747,'удины');
INSERT INTO nationalities (id,name) VALUES (748,'удморт');
INSERT INTO nationalities (id,name) VALUES (749,'удмурты');
INSERT INTO nationalities (id,name) VALUES (750,'удэ (с родными языками китайским и русским)');
INSERT INTO nationalities (id,name) VALUES (751,'удэ (с родным языком удэгейским)');
INSERT INTO nationalities (id,name) VALUES (752,'удэгейцы');
INSERT INTO nationalities (id,name) VALUES (753,'удэхе');
INSERT INTO nationalities (id,name) VALUES (754,'удэхейцы');
INSERT INTO nationalities (id,name) VALUES (755,'узбеки');
INSERT INTO nationalities (id,name) VALUES (756,'уйгуры');
INSERT INTO nationalities (id,name) VALUES (757,'уйльта');
INSERT INTO nationalities (id,name) VALUES (758,'укморт');
INSERT INTO nationalities (id,name) VALUES (759,'украинцы');
INSERT INTO nationalities (id,name) VALUES (760,'ульта');
INSERT INTO nationalities (id,name) VALUES (761,'ульча (с родным языком ульта)');
INSERT INTO nationalities (id,name) VALUES (762,'ульча (с родным языком ульчским)');
INSERT INTO nationalities (id,name) VALUES (763,'ульчи');
INSERT INTO nationalities (id,name) VALUES (764,'уназигмит');
INSERT INTO nationalities (id,name) VALUES (765,'унан''ах');
INSERT INTO nationalities (id,name) VALUES (766,'унанган');
INSERT INTO nationalities (id,name) VALUES (767,'уральские (восточные) марийцы');
INSERT INTO nationalities (id,name) VALUES (768,'урбуган');
INSERT INTO nationalities (id,name) VALUES (769,'урмей');
INSERT INTO nationalities (id,name) VALUES (770,'урморт');
INSERT INTO nationalities (id,name) VALUES (771,'уртморт');
INSERT INTO nationalities (id,name) VALUES (772,'урум');
INSERT INTO nationalities (id,name) VALUES (773,'ути');
INSERT INTO nationalities (id,name) VALUES (774,'фараоны');
INSERT INTO nationalities (id,name) VALUES (775,'фарс');
INSERT INTO nationalities (id,name) VALUES (776,'финны');
INSERT INTO nationalities (id,name) VALUES (777,'финны-ингерманландцы');
INSERT INTO nationalities (id,name) VALUES (778,'франк');
INSERT INTO nationalities (id,name) VALUES (779,'французы');
INSERT INTO nationalities (id,name) VALUES (780,'хаас');
INSERT INTO nationalities (id,name) VALUES (781,'хааш');
INSERT INTO nationalities (id,name) VALUES (782,'хай');
INSERT INTO nationalities (id,name) VALUES (783,'хайдаг');
INSERT INTO nationalities (id,name) VALUES (784,'хакасы');
INSERT INTO nationalities (id,name) VALUES (785,'халдеи');
INSERT INTO nationalities (id,name) VALUES (786,'халха');
INSERT INTO nationalities (id,name) VALUES (787,'халха-монголы халхасцы');
INSERT INTO nationalities (id,name) VALUES (788,'хальмг');
INSERT INTO nationalities (id,name) VALUES (789,'хамниганы');
INSERT INTO nationalities (id,name) VALUES (790,'хамшены');
INSERT INTO nationalities (id,name) VALUES (791,'хамшецы');
INSERT INTO nationalities (id,name) VALUES (792,'хангайцы');
INSERT INTO nationalities (id,name) VALUES (793,'хангук сарам');
INSERT INTO nationalities (id,name) VALUES (794,'хандеяры');
INSERT INTO nationalities (id,name) VALUES (795,'ханти');
INSERT INTO nationalities (id,name) VALUES (796,'ханты');
INSERT INTO nationalities (id,name) VALUES (797,'хантых');
INSERT INTO nationalities (id,name) VALUES (798,'хантэ');
INSERT INTO nationalities (id,name) VALUES (799,'хань');
INSERT INTO nationalities (id,name) VALUES (800,'ханьжэнь');
INSERT INTO nationalities (id,name) VALUES (801,'хванал');
INSERT INTO nationalities (id,name) VALUES (802,'хваршал');
INSERT INTO nationalities (id,name) VALUES (803,'хваршинцы');
INSERT INTO nationalities (id,name) VALUES (804,'хваршины');
INSERT INTO nationalities (id,name) VALUES (805,'хемшилы');
INSERT INTO nationalities (id,name) VALUES (806,'хемшины');
INSERT INTO nationalities (id,name) VALUES (807,'хинатбы');
INSERT INTO nationalities (id,name) VALUES (808,'хинди');
INSERT INTO nationalities (id,name) VALUES (809,'хиндиязычные индийцы');
INSERT INTO nationalities (id,name) VALUES (810,'хиндустанцы');
INSERT INTO nationalities (id,name) VALUES (811,'хновцы');
INSERT INTO nationalities (id,name) VALUES (812,'хойбал');
INSERT INTO nationalities (id,name) VALUES (813,'хойты');
INSERT INTO nationalities (id,name) VALUES (814,'хонгодоры');
INSERT INTO nationalities (id,name) VALUES (815,'хорваты');
INSERT INTO nationalities (id,name) VALUES (816,'хоринцы');
INSERT INTO nationalities (id,name) VALUES (817,'хошеуты');
INSERT INTO nationalities (id,name) VALUES (818,'хошуты');
INSERT INTO nationalities (id,name) VALUES (819,'хуани');
INSERT INTO nationalities (id,name) VALUES (820,'хугни');
INSERT INTO nationalities (id,name) VALUES (821,'хуй');
INSERT INTO nationalities (id,name) VALUES (822,'хуйцзу');
INSERT INTO nationalities (id,name) VALUES (823,'хунзалис .');
INSERT INTO nationalities (id,name) VALUES (824,'хунзалы');
INSERT INTO nationalities (id,name) VALUES (825,'хунуни');
INSERT INTO nationalities (id,name) VALUES (826,'хуфидж');
INSERT INTO nationalities (id,name) VALUES (827,'хуфцы');
INSERT INTO nationalities (id,name) VALUES (828,'хызыл');
INSERT INTO nationalities (id,name) VALUES (829,'цахуры');
INSERT INTO nationalities (id,name) VALUES (830,'цезы');
INSERT INTO nationalities (id,name) VALUES (831,'цонголы');
INSERT INTO nationalities (id,name) VALUES (832,'цунтинцы');
INSERT INTO nationalities (id,name) VALUES (833,'цыгане');
INSERT INTO nationalities (id,name) VALUES (834,'цыгане среднеазиатские');
INSERT INTO nationalities (id,name) VALUES (835,'чаан');
INSERT INTO nationalities (id,name) VALUES (836,'чаваш');
INSERT INTO nationalities (id,name) VALUES (837,'чавчу');
INSERT INTO nationalities (id,name) VALUES (838,'чавчувены');
INSERT INTO nationalities (id,name) VALUES (839,'чавчыв');
INSERT INTO nationalities (id,name) VALUES (840,'чалканцы');
INSERT INTO nationalities (id,name) VALUES (841,'чамалалы');
INSERT INTO nationalities (id,name) VALUES (842,'чамалинцы');
INSERT INTO nationalities (id,name) VALUES (843,'чаны');
INSERT INTO nationalities (id,name) VALUES (844,'чаты');
INSERT INTO nationalities (id,name) VALUES (845,'чаучу');
INSERT INTO nationalities (id,name) VALUES (846,'челканцы');
INSERT INTO nationalities (id,name) VALUES (847,'черемисы');
INSERT INTO nationalities (id,name) VALUES (848,'черкесогаи');
INSERT INTO nationalities (id,name) VALUES (849,'черкесы');
INSERT INTO nationalities (id,name) VALUES (850,'черногорцы');
INSERT INTO nationalities (id,name) VALUES (851,'чехи');
INSERT INTO nationalities (id,name) VALUES (852,'чеченцы');
INSERT INTO nationalities (id,name) VALUES (853,'чеченцы-аккинцы');
INSERT INTO nationalities (id,name) VALUES (854,'чжунго жэнь');
INSERT INTO nationalities (id,name) VALUES (855,'чосон сарам');
INSERT INTO nationalities (id,name) VALUES (856,'чуванцы');
INSERT INTO nationalities (id,name) VALUES (857,'чуваши');
INSERT INTO nationalities (id,name) VALUES (858,'чудь');
INSERT INTO nationalities (id,name) VALUES (859,'чукчи');
INSERT INTO nationalities (id,name) VALUES (860,'чулымские татары');
INSERT INTO nationalities (id,name) VALUES (861,'чулымские тюрки');
INSERT INTO nationalities (id,name) VALUES (862,'чулымцы');
INSERT INTO nationalities (id,name) VALUES (863,'чумыль-куп');
INSERT INTO nationalities (id,name) VALUES (864,'чуфут');
INSERT INTO nationalities (id,name) VALUES (865,'чухари');
INSERT INTO nationalities (id,name) VALUES (866,'чухонцы');
INSERT INTO nationalities (id,name) VALUES (867,'шалганы');
INSERT INTO nationalities (id,name) VALUES (868,'шапсуги');
INSERT INTO nationalities (id,name) VALUES (869,'шапсыг');
INSERT INTO nationalities (id,name) VALUES (870,'шведы');
INSERT INTO nationalities (id,name) VALUES (871,'шекты');
INSERT INTO nationalities (id,name) VALUES (872,'шелькуп');
INSERT INTO nationalities (id,name) VALUES (873,'шешкум');
INSERT INTO nationalities (id,name) VALUES (874,'шкарауа');
INSERT INTO nationalities (id,name) VALUES (875,'шкипетары');
INSERT INTO nationalities (id,name) VALUES (876,'шор-кижи');
INSERT INTO nationalities (id,name) VALUES (877,'шорцы');
INSERT INTO nationalities (id,name) VALUES (878,'шугнанцы');
INSERT INTO nationalities (id,name) VALUES (879,'шугни');
INSERT INTO nationalities (id,name) VALUES (880,'шугнони');
INSERT INTO nationalities (id,name) VALUES (881,'ывын');
INSERT INTO nationalities (id,name) VALUES (882,'эбраэли');
INSERT INTO nationalities (id,name) VALUES (883,'эбэн');
INSERT INTO nationalities (id,name) VALUES (884,'эвен');
INSERT INTO nationalities (id,name) VALUES (885,'эвенк');
INSERT INTO nationalities (id,name) VALUES (886,'эвенки');
INSERT INTO nationalities (id,name) VALUES (887,'эвены');
INSERT INTO nationalities (id,name) VALUES (888,'эвон');
INSERT INTO nationalities (id,name) VALUES (889,'эвримейсет');
INSERT INTO nationalities (id,name) VALUES (890,'эвын');
INSERT INTO nationalities (id,name) VALUES (891,'эвэн');
INSERT INTO nationalities (id,name) VALUES (892,'эвэс');
INSERT INTO nationalities (id,name) VALUES (893,'эзды');
INSERT INTO nationalities (id,name) VALUES (894,'элеты');
INSERT INTO nationalities (id,name) VALUES (895,'элканбэйэ');
INSERT INTO nationalities (id,name) VALUES (896,'эллинос');
INSERT INTO nationalities (id,name) VALUES (897,'элутыл''у');
INSERT INTO nationalities (id,name) VALUES (898,'элькан дэйнин');
INSERT INTO nationalities (id,name) VALUES (899,'энцы');
INSERT INTO nationalities (id,name) VALUES (900,'эньчо');
INSERT INTO nationalities (id,name) VALUES (901,'энэтэ');
INSERT INTO nationalities (id,name) VALUES (902,'эрзя');
INSERT INTO nationalities (id,name) VALUES (903,'эскимосы');
INSERT INTO nationalities (id,name) VALUES (904,'эстонцы');
INSERT INTO nationalities (id,name) VALUES (905,'эстонцы-сету');
INSERT INTO nationalities (id,name) VALUES (906,'эсты');
INSERT INTO nationalities (id,name) VALUES (907,'этели');
INSERT INTO nationalities (id,name) VALUES (908,'эуштинцы');
INSERT INTO nationalities (id,name) VALUES (909,'ээсти');
INSERT INTO nationalities (id,name) VALUES (910,'ээстилане');
INSERT INTO nationalities (id,name) VALUES (911,'юген');
INSERT INTO nationalities (id,name) VALUES (912,'юги');
INSERT INTO nationalities (id,name) VALUES (913,'юкагиры');
INSERT INTO nationalities (id,name) VALUES (914,'юпагыт');
INSERT INTO nationalities (id,name) VALUES (915,'юпит');
INSERT INTO nationalities (id,name) VALUES (916,'юртовские татары');
INSERT INTO nationalities (id,name) VALUES (917,'якуты (саха)');
INSERT INTO nationalities (id,name) VALUES (918,'якутяне');
INSERT INTO nationalities (id,name) VALUES (919,'ямские');
INSERT INTO nationalities (id,name) VALUES (920,'японцы');
INSERT INTO nationalities (id,name) VALUES (921,'ясколбинские татары');
INSERT INTO nationalities (id,name) VALUES (922,'яушта');
INSERT INTO nationalities (id,name) VALUES (923,'яхолшу');
INSERT INTO nationalities (id,name) VALUES (924,'яхуди');