INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (1, null, 'Қабанбай батыра', '180', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (2, null, 'Ораз Жумашев', '29', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (3, null, 'Наурыз', '62', 3);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (4, null, 'Райымбека', '44', 4);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (5, null, 'Кастеева', '12', 5);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (6, null, 'Арынова', '1', 6);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (7, null, 'Д.Қонаев', '24', 7);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (8, null, 'Ə.Жангелдин', '89А', 8);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (9, null, 'Акана-серэ', '24', 9);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (10, null, 'Жеңіс', '86', 10);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (11, null, 'Нурмагамбетова', '144', 11);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (12, null, 'Баймуханова', '45а', 12);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (13, null, 'улица 199', '1', 13);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (14, null, 'Отан', '17', 14);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (15, 2, 'Н.Назарбаева', '86', 15);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (16, null, 'Танирбергенова', '1', 16);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (17, null, 'Шулятикова', '64', 17);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (18, null, 'Муканова', '20', 18);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (19, 1, 'Кабанбай Батыра', '5', 19);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (20, null, 'Тауке хана', '24', 20);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (21, null, 'Кунаева', '92', 21);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (22, null, 'Ж.Молдагалиева', '18', 22);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (23, null, 'Молодежная', '29', 23);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (24, null, 'Казахстанская', '15А', 24);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (25, null, 'Караменде би', '17', 25);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (26, null, 'Байконурова', '123', 26);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (27, null, 'Тəеулсіздік', '118', 27);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (28, null, '6 микрорайон', '56', 28);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (29, null, 'Мауленова', '26', 29);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (30, null, 'Тажибаева', '18а', 30);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (31, null, 'Балқы Базар', '19А', 31);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (32, null, 'Үрзімат Мадиев', '51', 32);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (33, null, 'Ж.Нұрмағанбетұлы', '128', 33);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (34, null, '15-й микрорайон', '31', 34);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (35, null, 'Косай ата', '15', 35);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (36, null, 'Отырар', '65а', 36);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (37, null, 'Толстого', '99', 37);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (38, null, 'Энергетиков', '54А', 38);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (39, null, 'Ауэзова', '6', 39);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (40, null, 'Конституции Казахстана', '60', 40);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (41, null, 'Ауельбекова', '2А', 41);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (42, null, 'Конституция Казахстана', '261', 42);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (43, null, '1 мкр', '24В', 43);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (44, 2, 'Қажымұқан', '77', 44);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (45, null, 'Əйтеке би', '3А', 45);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (46, null, 'Шəмші гүлзары', '21а', 46);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (47, null, 'Тоқпанбетов', '1а', 47);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (48, null, 'М.Озтурик', '13', 48);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (49, null, 'Толе Би', '94', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (50, null, 'Кабанбай Батыра', '53', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (51, null, 'Казахстан', '55', 18);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (52, null, 'Мәңгілік Ел', '11', 19);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (53, null, 'Жибек Жолы', '184', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (54, null, 'Пушкина', '111', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (55, null, 'проспект Алашахана', '1-Б', 29);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (56, null, 'проспект «Сарыарқа»', '33', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (57, null, 'Ахмет Жубанова', '7', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (58, null, 'Гоголя', '40', 27);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (59, null, 'Абая', '76', 12);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (60, null, 'Байтурсынова', '47', 30);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (61, null, 'Егизбаева', '13', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (62, null, 'Худина', '5', 15);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (63, null, 'Джамбула ', '35', 26);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (64, null, 'Утепова ', '29', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (65, null, 'Юбилейная ', '14', 43);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (66, null, 'Пушкина', '86', 43);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (67, null, 'Г.Иляева', '16', 3);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (68, null, 'Достык', '13', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (69, null, 'Колбасшы Койгельды', '171', 23);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (70, null, 'пр-т Сейфуллина', '521', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (71, null, 'Желтоксан', '69Б', 23);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (72, null, 'Г.Иляева', '3', 3);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (73, null, 'пр. Абая', '8А', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (74, null, 'Мадели кожа', '137', 3);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (75, null, 'Ермекова', '124', 27);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (76, null, 'Жандосова', '53', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (77, null, 'Курсантская', '1', 9);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (78, null, 'Тауелсыздык', '77', 4);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (79, null, 'Б.Момышулы', '36', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (80, null, 'Г. Муратбаева', '43', 33);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (81, null, 'пр.А.Молдагуловой', '34', 9);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (82, null, 'Протозанова', '69', 18);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (83, 1, 'Ихсанова', '44', 25);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (84, null, 'Жубанова', '7', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (85, null, 'Закарпатская', '44', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (86, null, 'пр.Жеңіс', '62', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (87, null, 'Абая', '103', 19);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (88, null, 'проспект Туран', '72', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (89, null, 'проспект Республики', '30', 52);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (90, null, 'Тәуелсіздік ', '118', 30);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (91, null, 'Кайым Мухамедханова', '37А', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (92, null, 'Торекулова', '71', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (93, null, 'Айтеке би', '29А', 33);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (94, null, 'Абылай хана', '86', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (95, null, 'Ауэзова', '189А', 12);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (96, null, 'Сулейменова', '6', 23);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (97, null, 'Ауезова', '11', 51);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (98, null, 'Ы. Дукенулы', '29', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (99, null, 'Джансдосова', '60а', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (100, null, 'проспект Алии Молдагуловой', '39', 9);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (101, null, 'Шевченко', '97', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (102, null, 'Есенберлина', '25', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (103, null, 'Бр.Жубановых', '302а', 9);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (104, null, 'проспект М.Жумабаева', '4', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (105, null, 'Ауельбекова', '17', 32);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (106, null, 'Жансугурова', '187А', 4);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (107, null, 'Танирбергенова', '1', 19);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (108, null, 'проспект Абая', '11', 30);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (109, null, 'Сатпаева', '2а', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (110, null, 'Тәуелсіздік', '50', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (111, 1, 'Байтурсынова', '126', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (112, null, 'Толе би', '100', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (113, null, 'Жангир хана', '51', 25);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (114, null, 'Бульвар мира', '56', 27);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (115, null, 'Мира', '60', 40);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (116, null, 'проспект Достык', '103', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (117, 4, 'М.Горького', '102', 40);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (118, null, 'Демесинова', '38', 33);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (119, null, 'Бажова', '68', 18);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (120, null, 'Чернышевского', '59', 30);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (121, null, 'Павлова', '30', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (122, null, 'Сатпаева', '18а', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (123, null, 'Байтурсынова', '107', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (124, null, 'Пичугина', '259', 27);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (125, null, 'Толе би', '62', 23);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (126, null, 'пл. аль-Фараби', '1', 3);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (127, null, 'Аль-Фараби', '73', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (128, null, 'Наурызбай батыра', '9', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (129, null, 'Байсеитова', '5', 19);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (130, null, 'пр. Абая', '8А', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (131, null, 'Жандосова', '59', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (132, null, 'Панфилова', '127', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (133, null, 'проспект Студенческий', '1', 15);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (134, null, 'Акан-Сери', '136', 12);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (135, null, 'Рыскулбекова', '28', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (136, null, 'пр.Достык', '162', 25);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (137, null, 'Университетская', '28', 27);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (138, null, 'Абая', '2', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (139, null, 'Коргалжинское шоссе', '8', 1);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (140, null, 'Маресьева', '68', 9);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (141, null, 'Ломова', '64', 40);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (142, null, 'пр.аль-Фараби', '71', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (143, null, 'Айтеке би', '52', 9);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (144, null, 'Ерубаева', '16', 27);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (145, null, 'Герцена', '27', 30);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (146, null, 'Розыбакиева', '227', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (147, null, 'Абая', '31а', 33);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (148, 1, 'Абылай хана', '1', 53);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (149, null, 'Курманбеков', '4', 3);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (150, null, 'Красногорская', '4', 2);
INSERT INTO public.streets (id, fraction, name, number, locality_id) VALUES (151, null, 'Муратбаева', '200', 2);